###############################################################
#  Generated by:      Cadence Innovus 25.13-s088_1
#  OS:                Linux x86_64(Host ID vlsi.iitgn.ac.in)
#  Generated on:      Mon Jun  1 15:32:57 2026
#  Design:            riscv_top
#  Command:           saveDesign ../outputs/3_powerplan.enc
###############################################################

################################################
#  Preference File                             #
################################################

################################################
#  Syntax for Design-related/non-color pref:   #
#  setPreference <preference_name> <value>     #
################################################
setPreference DesignHierChar {/}
setPreference DEFHierChar {/}
setPreference PDEFBusDelim {[]}
setPreference CmdLogMode 1
setPreference LogTypeInCmd 0
setPreference logviewer 0
setPreference MouseGestures 1

################################################
#  Syntax for Display-related/non-color pref:  #
#  setPreference <preference_name> <value>     #
################################################
setPreference MinFPModuleSize 100
setPreference MinFlightLineWidth 1
setPreference MaxFlightLineNetTerms 500
setPreference LevelFlight 1
setPreference DirectionSink 1
setPreference DirectionSource 1
setPreference HiliteNetWhenQueryObj 0
setPreference HiliteShapeWhenSelectNet 0
setPreference SelectNetWhenSelectPin 0
setPreference HiliteNetWhenSelectPin 1
setPreference HiliteNetWhenSelectWire 1
setPreference QueryWireNet 0
setPreference ControlPinSelectabilityByInstance 1
setPreference OnlySelectHighlighted 0
setPreference SelectByArea 0
setPreference WinSelectMargin 8
setPreference ShowNumberBlockConnection 0
setPreference StrecthRestriction 0
setPreference StretchRectilinear 0
setPreference MoveRestriction 0
setPreference DisplayRelFPlan 1
setPreference LegalizeMacro 0
setPreference DisplayPtnPin 1
setPreference DisplayFPlanFlightLine 1
setPreference DisplayPinName 0
setPreference DisplayBusGuideAsLine 0
setPreference CopyNetKeepNetName 1
setPreference InstanceText Instance
setPreference ShowNetFullName 0
setPreference ShowNetNameWithLayerColor 0
setPreference TermCrossPix 4
setPreference hInstInnerText t
setPreference ExclusiveFlight 0
setPreference ShowToUnplace 0
setPreference FlightLineInMove 1
setPreference AutoRedraw 1
setPreference ShowViaMetal 0
setPreference IgnoreAmoebaRatio 0
setPreference DisplayCellPattern 0
setPreference DrawInstByPlaceStatus 1
setPreference DrawWireByWireStatus 1
setPreference ShowCrossLineWhenSelect 1
setPreference FullViewOutsideDieArea 0
setPreference UseDigitFillPattern 1
setPreference DisplayCutPattern 1
setPreference DrawDetailWhenMoveVia 1
setPreference TurnOnLayersWhenEditWire 1
setPreference DisplayIndicatorOfViaPillar 0
setPreference ShowMarkerWhenDim 0
setPreference ShowConnectionInOutNumber 0
setPreference ConnectionColorType 0
setPreference OnlyBundleNetFlight 0
setPreference FromOutputPin 0
setPreference ShowFlightLineTermMark 0
setPreference BlockFlightLine 1
setPreference InstFlightLine 1
setPreference ModuleFlightLine 1
setPreference IoCellFlightLine 1
setPreference BlackBoxFlightLine 1
setPreference ShowConnectionWithWidth 0
setPreference FLWidthThresholdLow 20
setPreference FLWidthThresholdHigh 80
setPreference percentageOfPan 30
setPreference marginOfZoomSelected 50
setPreference scaleOfZoom 3.0
setPreference WheelZoomWithModify 0
setPreference ShowBothInputConnection 0
setPreference ShowNetWeightConnection 1
setPreference ShowFlightLineThruPtnPin 0
setPreference ShowLayerDirection 0
setPreference GDSLayerTransPercent 0
setPreference ShowAttrPopup 1
setPreference EnlargeLogicalPin 1
setPreference ShowDelBox 0
setPreference SelectByLine 0
setPreference SelectStickyMode 0
setPreference ShowUnplacedInst 0
setPreference ShowRectilinearPad 0
setPreference zoomPrevCount 9
setPreference saveManually 0
setPreference noInsideMacro 0
setPreference noInsidePartition 0
setPreference enlargeFitViewFL 0
setPreference ShowParentModule 0
setPreference ShowChildPartition 0
setPreference ShowParentPartition 0
setPreference ShowAllFence 0
setPreference SkipBufferFlightline 0
setPreference ShowFPObjInPlace 0
setPreference DrawFlightlineLast 0
setPreference DetailDisplayFactor 16
setPreference DoubleClickTime 400
setPreference SingleLayerMode 0
setPreference QuerySkipInst 0
setPreference QuerySkipInstObs 0
setPreference QuerySkipInstPin 0
setPreference QuerySkipRegular 0
setPreference QuerySkipSpecial 0
setPreference ShowModuleText 1
setPreference ShowAmoebaModuleText 1
setPreference ShowRowSiteText 1
setPreference ShowIoPadText 1
setPreference ShowInstanceText 1
setPreference ShowInstancePinText 1
setPreference ShowIoPinText 1
setPreference ShowGroupText 1
setPreference ShowBumpText 1
setPreference ShowClockTreeText 1
setPreference ShowChannelText 1
setPreference ShowLefPortNumText 1
setPreference ShowMacroSitePtnText 1
setPreference ShowSIPFingerText 1
setPreference ShowNetText 1
setPreference ShowUtilizationText 1
setPreference TextDisplaySize a
setPreference UseTargetUtil 1
setPreference UseEffectiveUtil 0
setPreference UseStdUtil 0
setPreference AutoDetailDisplay 0

################################################
#  Syntax for Floorplan-related/non-color pref:#
#  setPreference <preference_name> <value>     #
################################################
setPreference CloneSnapMaster 0

################################################
#  Syntax for Comgestion Map related pref:     #
#  setPreference <preference_name> <value>     #
################################################
setPreference VertViolation 0.0
setPreference HorzViolation 0.0
setPreference congestionMap_nrStyle 1
setPreference congestionMap_trStyle 0
setPreference congestionMap_range0 -2
setPreference congestionMap_color0 0
setPreference congestionMap_range1 -1
setPreference congestionMap_color1 0
setPreference congestionMap_range2 0
setPreference congestionMap_color2 1
setPreference congestionMap_range3 1
setPreference congestionMap_color3 2
setPreference congestionMap_range4 2
setPreference congestionMap_color4 3
setPreference congestionMap_range5 3
setPreference congestionMap_color5 5
setPreference congestionMap_range6 4
setPreference congestionMap_color6 9
setPreference congestionMap_range7 5
setPreference congestionMap_color7 11
setPreference congestionMap_range8 6
setPreference congestionMap_color8 11
setPreference congestionMap_range9 27
setPreference congestionMap_color9 11
setLayerPreference congestH -isVisible 0
setLayerPreference congestV -isVisible 0
setLayerPreference congestObj -isVisible 0

################################################
#  Syntax for display threshold related pref:   #
#  setPreference <preference_name> <value>     #
################################################
setPreference SpeedLevel 0
setPreference HighlightColorNumber 64

################################################
#  Syntax for flightline color related pref:   #
#  setPreference <preference_name> <value>     #
################################################
setPreference SingleConnectionColor cyan

################################################
#  Syntax for attribute summary of             #
#  object attribute related pref:              #
#  setPreference <preference_name> <value>     #
################################################
setPreference attribute_summary_actual_scan_chain "analyzed base_name compressed connected_shift_enable dft_hookup_pin_sdi dft_hookup_pin_sdo dft_partition domain edge elements escaped_name head_lockup mode_name name non_shared_scan_out obj_type other_clocks power_domain reg_count scan_clock_a scan_clock_b scan_in scan_out sdi_compression_signal shared_input shared_output shared_select shift_enable terminal_lockup"
setPreference attribute_summary_flow "end_steps feature_values features name obj_type owner run_count skip_metric start_steps steps tool tool_options"
setPreference attribute_summary_interposer_route_rule "layer net obj_type offset spacing width"
setPreference attribute_summary_special_via "bottom_mask bottom_rects bottom_rects_mask cut_mask cut_rects cut_rects_mask net obj_type point shape shield_net status top_mask top_rects top_rects_mask user_class via_def"
setPreference attribute_summary_inst_obs_shape "inst is_ignore_pg_net layer mask obj_type polygon rect spacing type"
setPreference attribute_summary_shape "mask obj_type polygon rect type"
setPreference attribute_summary_flexible_htree "cts_flexible_htree_adjust_sink_grid_for_aspect_ratio cts_flexible_htree_auto_sinks cts_flexible_htree_auto_sinks_rects cts_flexible_htree_auto_sinks_sink_area cts_flexible_htree_final_cell cts_flexible_htree_hv_balance cts_flexible_htree_image_directory cts_flexible_htree_inverting cts_flexible_htree_layer_density cts_flexible_htree_max_driver_distance cts_flexible_htree_max_root_distance cts_flexible_htree_mode cts_flexible_htree_omit_symmetry cts_flexible_htree_partition_boundary_polarity cts_flexible_htree_partition_groups cts_flexible_htree_power_weight cts_flexible_htree_root cts_flexible_htree_sink_grid cts_flexible_htree_sink_grid_box cts_flexible_htree_sink_grid_exclusion_areas cts_flexible_htree_sink_grid_sink_area cts_flexible_htree_sink_instance_prefix cts_flexible_htree_sinks cts_flexible_htree_stop_at_sdc_clock_roots cts_flexible_htree_trunk_cell cts_route_type_flexible_htree cts_route_type_flexible_htree_backside insts name nets obj_type"
setPreference attribute_summary_base_cell "base_pins bbox areaclass is_buffer is_inverter is_sequential name pg_base_pins site "
setPreference attribute_summary_opcond "base_name is_virtual name obj_type process temperature tree_type voltage"
setPreference attribute_summary_attribute "additional_help base_name category check_function compute_function data_type default_value help indices is_computed is_settable is_user_defined name obj_type parent possible_values set_function skip_in_db"
setPreference attribute_summary_place_blockage "base_name density inst is_no_flop is_pushdown name obj_type rects shapes type"
setPreference attribute_summary_rc_corner "cap_table_file is_active is_dynamic is_hold is_leakage is_setup name obj_type post_route_cap post_route_clock_cap post_route_clock_cross_cap post_route_clock_res post_route_cross_cap post_route_res pre_route_cap pre_route_clock_cap pre_route_clock_res pre_route_res qrc_tech_file temperature thru_substrate_subckt_file via_variation_file"
setPreference attribute_summary_violation "base_name description endpoints escaped_name fixed id name obj_type reg_count registers root_node segments tristate_net_drivers tristate_net_load type"
setPreference attribute_summary_port "direction hnet layer location name net place_status slack_max slack_min width "
setPreference attribute_summary_delay_noise_obj "annotated_glitch attackers capacitance coupling_capacitance glitch_area glitch_width hierarchical_name input_failure_threshold input_peak input_peak_slack level num_active_attackers num_attackers obj_type propagated_glitch receiver_peak receiver_peak_slack receiver_peak_threshold resistance transition view_type"
setPreference attribute_summary_via_def "bottom_layer bottom_rects bottom_rects_mask cut_class cut_columns cut_layer cut_rects cut_rects_mask cut_rows cut_size from_design from_lib is_default is_non_default name obj_type resistance tech top_layer top_rects top_rects_mask via_def_rule"
setPreference attribute_summary_skew_group "cts_constrains cts_extracted_from_clock_name cts_extracted_from_constraint_mode_name cts_extracted_from_delay_corners cts_ignore_pins cts_include_source_latency cts_last_target_insertion_delay cts_last_target_skew cts_max_buffer_depth cts_sinks cts_sinks_active cts_skew_group_sources cts_target_insertion_delay cts_target_skew name "
setPreference attribute_summary_scan_chain "base_name body complete compressed dft_hookup_pin_sdi dft_hookup_pin_sdo dft_partition domain edge escaped_name head max_length name non_shared_scan_out obj_type scan_clock_a scan_clock_b scan_in scan_out sdi_compression_signal shared_input shared_output shared_select shift_enable tail terminal_lockup"
setPreference attribute_summary_timing_point "arrival arrival_mean arrival_sigma arrival_skewness clock_unroll_adjustment delay delay_effective delay_mean delay_sigma delay_skewness delta_delay direction hierarchical_name is_fanin_arc_cell_arc is_hierarchical load local_ref_clock local_slack local_slack_adjusted net obj_type pin si_object slack slack_mean slack_sigma slack_skewness slew slew_mean slew_sigma slew_skewness spatial_derate spatial_derate_sigma ssi_derate total_derate total_derate_sigma transition_type user_derate user_derate_sigma voltage"
setPreference attribute_summary_foreign_cell "name obj_type orient point"
setPreference attribute_summary_resize_blockage "is_resizeable name obj_type rect"
setPreference attribute_summary_clock_spine "name obj_type"
setPreference attribute_summary_bus_sink_group "name obj_type sinks"
setPreference attribute_summary_design "analysis_views bbox local_hinsts name num_insts num_netspg_ports ports power_domains "
setPreference attribute_summary_clock_tree "cts_buffer_cells cts_clock_gating_cells cts_clock_tree_source_group cts_clock_tree_source_pin cts_clone_clock_gates cts_clone_clock_logic cts_delay_cells cts_generated_by_sinks cts_inverter_cells cts_last_target_max_transition_time cts_leaf_buffer_cells cts_leaf_inverter_cells cts_logic_cells cts_parents cts_route_type cts_source_driver cts_source_group_clock_trees cts_source_input_max_transition_time cts_source_latency cts_source_max_capacitance cts_target_max_capacitance cts_target_max_transition_time cts_top_buffer_cells cts_top_inverter_cells name "
setPreference attribute_summary_stack_via_rule "name obj_type"
setPreference attribute_summary_layer_rule "layer obj_type spacing width"
setPreference attribute_summary_message "base_name count long_help max_print message name obj_type on_error severity"
setPreference attribute_summary_via_def_rule "bottom_enclosure bottom_layer bottom_width cut_layer cut_rect cut_spacing name obj_type resistance_per_cut tech top_enclosure top_layer top_width"
setPreference attribute_summary_pg_pin "base_name effective_stack_via_rule escaped_name hnet inst name net obj_type pg_base_pin route_max_fanout stack_via_rule stack_via_rule_required"
setPreference attribute_summary_context_data "all_block_clocks all_top_clocks obj_type top_instance top_view unmapped_block_clocks unmapped_top_clocks"
setPreference attribute_summary_route_blockage "base_name density design_rule_width inst is_except_pg_net is_fixed is_no_wrong_way is_only_pg_net is_pushdown layer name obj_type rects shapes spacing type"
setPreference attribute_summary_inst "base_cell bbox location name orient pins place_status"
setPreference attribute_summary_net "drivers hnets loads name num_drivers num_loads route_rule shield_nets "
setPreference attribute_summary_pin "base_pin direction hnet inst layerlocation name net slack_max slack_min "
setPreference attribute_summary_shape_via "bottom_mask bottom_rects cut_mask cut_rects location obj_type top_mask top_rects via_def"
setPreference attribute_summary_route_type "base_name bottom_mask_layer_num bottom_one_side_layer_num bottom_preferred_layer driver_use_multi_cut_via em_route_rule em_route_rule_distance is_table mask min_stack_layer name obj_type route_effort route_rule shield_net shield_side shield_tap_instance_insertion_effort stack_distance top_mask_layer_num top_one_side_layer_num top_preferred_layer"
setPreference attribute_summary_bus "bits lsb msb name obj_type"
setPreference attribute_summary_level_shifter_rule "applies_to applies_to_boundary domain elements exclude_elements input_supply location name no_shift obj_type output_supply rule sink source"
setPreference attribute_summary_test_clock "at_speed base_name blocking_se controllable controllable_from dft_hookup_pin dft_hookup_polarity divide_fall divide_period divide_rise domain_se escaped_name fall function name obj_type off_state period rise root_source_pins root_source_polarity sources user_defined_signal"
setPreference attribute_summary_clock "clock_network_pins delay_max_fall delay_max_rise delay_min_fall delay_min_rise divide_by generated_clocks is_active is_combinational_source_path is_generated is_inverted master_clock master_source name period sources view_name "
setPreference attribute_summary_power_switch_rule "ack_port control_port domain input_supply_port name obj_type off_state on_state output_supply_port supply_set"
setPreference attribute_summary_def_scan_chain "end floating_insts max_bits name obj_type ordered_insts scan_partition scan_pins start"
setPreference attribute_summary_layer_shape "is_ignore_pg_net layer obj_type obs_type shapes spacing"
setPreference attribute_summary_group "area base_name constraint_type density exclusive_group_gap exclusive_group_type exclusive_groups is_floating members name obj_type parent power_domain rects safety_dcls_isolate_clock safety_dcls_isolate_inputs safety_dcls_isolate_is_halo safety_dcls_isolate_outputs safety_dcls_isolate_reset safety_dcls_isolate_scan_enable safety_dcls_isolate_use_halo safety_dcls_route_use_halo safety_failure_mode safety_mechanism safety_mechanism_type"
setPreference attribute_summary_analysis_view "constraint_mode delay_corner is_active is_dormant is_drv is_dynamic is_em is_hold is_hold_default is_ir is_leakage is_setup is_setup_default latency_file name obj_type power_modes"
setPreference attribute_summary_arc "delay_max_fall delay_max_rise delay_min_fall delay_min_rise from_pin is_cellarc is_disabled lib_arcs mode sense timing_type to_pin when when_end when_start "
setPreference attribute_summary_pin_blockage "excluded_pins included_pins layer name obj_type rect"
setPreference attribute_summary_clock_tree_source_group "clock_trees is_active name obj_type"
setPreference attribute_summary_ndr_eol_spacing "layer obj_type spacing within"
setPreference attribute_summary_special_wire "area begin_extension end_extension has_trim_metal is_patch layer mask net obj_type path polygon rect shape shield_net status trim_metal_color trim_metal_rect type user_class width"
setPreference attribute_summary_pg_base_pin "base_cell base_name direction effective_stack_via_rule is_always_on name obj_type pg_type physical_direction physical_pins route_bottom_preferred_layer route_max_fanout route_pattern route_preferred_layer_effort route_rule route_stripe_layer_range route_top_preferred_layer stack_via_required stack_via_rule_list stack_via_rule_required taper_rule tech tied_to use"
setPreference attribute_summary_sdp "bbox flip hier_name insts is_placed is_top justify_by local_list location name obj_type orient padding parent pin_alignment pin_names sdps snap_row_site_index space type"
setPreference attribute_summary_what_if_via "bottom_layer cut_layer cut_rect net obj_type top_layer"
setPreference attribute_summary_path_group "name obj_type"
setPreference attribute_summary_isolation_rule "applies_to applies_to_boundary clamp_value diff_supply_only domain elements exclude_elements isolation_sense isolation_signal isolation_supply location name no_isolation obj_type sink source"
setPreference attribute_summary_dft_configuration_mode "base_name current_mode decoded_pin escaped_name mode_enable_high mode_enable_low name obj_type type usage user_defined"
setPreference attribute_summary_gui_text "gui_layer_name height label location obj_type orient"
setPreference attribute_summary_trim_grid "group layer mask obj_type offset on_track pitch track_count track_index"
setPreference attribute_summary_package_object "die_net_name layer_name name obj_type package_net_name pt size type"
setPreference attribute_summary_partition "base_pins clones is_black_box is_commited master name pin_bottom_layers pin_left_layers pin_right_layers pin_top_layers route_halo_bottom_layer route_halo_to_boundary route_halo_top_layer "
setPreference attribute_summary_bump "base_cell base_name bbox bump_connect_target bump_pins center escaped_name foreign_excluded_center is_fixed_assignment location name net obj_type orient place_status ports"
setPreference attribute_summary_root "analysis_views base_cells constraint_modes current_design delay_corners flows hinsts layers libraries library_sets log_file modules opconds partitions pg_nets ports power_domains rc_corners "
setPreference attribute_summary_timing_path "arrival capture_clock_path capturing_clock capturing_point clock_path_end_point hold is_clock_gating_hold is_clock_gating_setup is_transparent_latch launch_clock_path launching_clock launching_point path_group_name path_type required_time setup slack timing_points view_name "
setPreference attribute_summary_test_signal "active atpg_use base_name dedicated_pin default_shift_enable dft_compression_signal dft_hookup_pin dft_hookup_polarity divide_fall divide_period divide_rise escaped_name fall function has_fanout ideal index lec_value master_signal name obj_type period pin pmbist_use rise scan_shift type user_defined_signal wir_reset_value wir_signal wir_tm_value"
setPreference attribute_summary_virtual_wire "begin_layer begin_point end_layer end_point net obj_type status"
setPreference attribute_summary_delay_corner "default_early_timing_condition default_late_timing_condition early_irdrop_files early_pg_net_voltages early_rc_corner early_temperature_files early_timing_condition early_timing_condition_string is_active is_dynamic is_hold is_leakage is_setup is_si_enabled late_irdrop_files late_pg_net_voltages late_rc_corner late_temperature_files late_timing_condition late_timing_condition_string name obj_type pg_net_voltages"
setPreference attribute_summary_gcell "base_name demand horizontal_demand horizontal_remaining horizontal_supply index name obj_type rect remaining supply vertical_demand vertical_remaining vertical_supply"
setPreference attribute_summary_preferred_cell_stripe "name obj_type"
setPreference attribute_summary_gui_polygon "gui_layer_name name obj_type pixel_width points"
setPreference attribute_summary_io_constraint "area bbox indent inst is_assigned is_corner is_gap_fixed is_ground is_offset_fixed is_power name obj_type offset order row side spacing term type"
setPreference attribute_summary_obj_type "accept_user_defined_attributes attributes help name obj_type"
setPreference attribute_summary_seq_function "base_name d_function escaped_name lib_cell name obj_type"
setPreference attribute_summary_tap_distance_rule "default name obj_type tap_layer_distances"
setPreference attribute_summary_hport_bus "base_name bits direction escaped_name hinst lsb msb name obj_type"
setPreference attribute_summary_via "bottom_mask bottom_rects bottom_rects_mask cut_mask cut_rects cut_rects_mask location net obj_type route_rule status top_mask top_rects top_rects_mask via_def"
setPreference attribute_summary_constraint_mode "ilm_sdc_files is_active is_dynamic is_hold is_leakage is_setup name obj_type sdc_files tcl_vars"
setPreference attribute_summary_base_pin "base_cell direction is_always_on layer name pg_type physical_pins use "
setPreference attribute_summary_context_top_clock "hierarchical_name obj_type"
setPreference attribute_summary_gui_rect "gui_layer_name name obj_type pixel_width rect"
setPreference attribute_summary_flow_step "begin_tcl body_tcl categories check_tcl description end_steps end_tcl exclude_time_metric feature_values features name obj_type owner run_count skip_db skip_metric start_steps status"
setPreference attribute_summary_tap_layer_distance "distance layer obj_type"
setPreference attribute_summary_physical_pin "class layer_shapes obj_type port_number shape_vias"
setPreference attribute_summary_net_group "exclude_net is_compact is_guided is_mixed_signal is_optimize_order is_spread keep_out_space name nets obj_type spacing"
setPreference attribute_summary_pin_group "base_pins exclude_pin is_compact is_guided is_spread keep_out_space name obj_type optimize_order parent pin_spacing"
setPreference attribute_summary_tech "base_cells base_pins layers lef_files name obj_type pg_base_pins route_rule sites stack_via_rules tap_distance_rules via_def_rules via_defs"
setPreference attribute_summary_gui_line "arrow gui_layer_name name obj_type pixel_width points"
setPreference attribute_summary_gcell_grid "direction num_grids obj_type start step"
setPreference attribute_summary_boundary "area bbox hinst is_floating obj_type rects type"
setPreference attribute_summary_pin_guide "area layer_priority layers name net_group obj_type parent pin_group rects"
setPreference attribute_summary_site "base_name class density_in_design name obj_type row_pattern size symmetry tech"
setPreference attribute_summary_port_shape "layer mask name net obj_type polygon port rect type"
setPreference attribute_summary_library "default_power_rail default_wireload files lib_cells name nominal_process nominal_temperature nominal_voltage power_rails slew_derate_from_library wireload_models "
setPreference attribute_summary_layer "cut_index direction min_spacing min_width name num_masks pitch_x pitch_y route_index type width "
setPreference attribute_summary_hport "base_name bus clock_gating_exclude_signal dft_dedicated_wrapper_reason dft_driven_by_clock direction escaped_name hdl_vname hinst hnet hpin is_booth_encoded lp_asserted_probability lp_asserted_toggle_rate lp_system_asserted_probability lp_system_asserted_toggle_rate lssd_master_clock name obj_type original_name wrapper_control wrapper_segment wrapper_type"
setPreference attribute_summary_timing_condition "library_sets name obj_type opcond opcond_library"
setPreference attribute_summary_lib_cell "async_clear_pins async_preset_pins base_cell bit_width clock_pins data_pins latch_enable_pins leakage_power lib_arcs lib_pins library name pg_lib_pins timing_model_type "
setPreference attribute_summary_scan_segment "active base_name clock clock_edge clock_gating_shift_enable connected_scan_clock_a connected_scan_clock_b connected_shift_enable core_wrapper core_wrapper_ports core_wrapper_type core_wrapper_usage ctl_defined dft_dont_scan dft_exclude_abstract_segment_from_los_pipeline dft_hookup_pin_sdi dft_hookup_pin_sdo dft_part_of_segment dft_partition dft_status dft_tail_test_clock dft_tail_test_clock_edge dft_tail_test_clock_waveform_edge dft_test_clock dft_test_clock_edge dft_test_clock_waveform_edge dft_violation elements escaped_name head_skew_safe instance model_defined name obj_type other_clocks power_domain reg_count reorderable scan_in scan_out shift_enable skew_safe tail_clock tail_clock_edge test_modes type user_defined_segment"
setPreference attribute_summary_hpin_bus "base_name bits direction escaped_name hinst lsb msb name obj_type"
setPreference attribute_summary_row "base_name name num_x num_y obj_type orient rect site step_x step_y"
setPreference attribute_summary_bump_grid "layers name obj_type origin pitch_x pitch_y"
setPreference attribute_summary_test_clock_domain "base_name escaped_name name obj_type"
setPreference attribute_summary_marker "bbox is_false is_hidden layer message message_id obj_type objects originator polygon subtype type user_originator user_subtype user_type"
setPreference attribute_summary_bump_pin "base_name base_pin bump direction escaped_name layer location name obj_type port"
setPreference attribute_summary_resistor "capacitance current current_direction em_jmax_dc_avg_ratio em_jmax_dc_rms_ratio failure_in_time layer length location name net node_names node_reff node_voltage_drop node_voltages obj_type resistance switch_net what_if_capacitance what_if_resistance width"
setPreference attribute_summary_text "alignment drafting font_name font_number height label layer oa_purpose obj_type orient point"
setPreference attribute_summary_lib_pin "base_pin capacitance direction fanout_load from_lib_arcs lib_cell name to_lib_arcs "
setPreference attribute_summary_antenna_model "area_factor area_factor_diff_use_only area_ratio cum_area_ratio cum_routing_plus_cut cum_side_area_ratio gate_minus_diff obj_type side_area_factor side_area_factor_diff_use_only side_area_ratio"
setPreference attribute_summary_package_component "cell_name inst_name obj_type pt ref_design size"
setPreference attribute_summary_hinst "apply_booth_encoding area base_name bbox boundary clock_gating_test_signal dft_abstract_dont_scan dft_dont_scan dft_exclude_flop_from_los_pipeline dft_force_blackbox_for_atpg dft_hier_instance_for_dedicated_wrapper dft_is_blackbox_for_atpg dft_is_los_pipeline_flop dft_part_of_segment dft_partition dft_scan_chain dft_scan_chain_in_multi_mode dont_retime dont_touch dont_touch_effective dont_touch_file dont_touch_hports dont_touch_sources dont_use_cells dont_use_cells_effective dp_sharing dpopt_instance_constant_input_based_speculation escaped_name exceptions fcu_instruction_set group hdl_proc_name hdl_vname hinsts hnets hpin_busses hpins hport_busses hports ilm_inst instance_internal_power instance_leakage_power insts is_ilm is_partition_defined local_hinsts local_hnets local_hpins local_insts local_pins lp_clock_gating_test_signal lp_dynamic_analysis_scope merge_combinational_hier_instance module name num_exceptions obj_type orient original_name original_names_for_split parent part_power_intent_file partition pmbist_instruction_set power_domain power_dynamic power_internal power_leakage power_switching power_toggle_rate power_total propagate_constant_from_timing_model read_only read_only_effective ref_name retime_original_registers single_bit_original_name trace_retime ungroup_allowed unresolved use_cells"
setPreference attribute_summary_route_rule "base_name eol_spacing is_from_lib is_hard_spacing layer_rules min_cuts name obj_type tech via_defs"
setPreference attribute_summary_retention_rule "domain elements exclude_elements name no_retention obj_type restore_condition restore_signal retention_supply save_condition save_signal zero_pin_live_slave_clock_isolation_cell zero_pin_live_slave_reset_isolation_cell zero_pin_live_slave_set_isolation_cell"
setPreference attribute_summary_hpin "base_name boundary_feedthru boundary_optimize_constant_hpins boundary_optimize_equal_opposite_hpins boundary_optimize_feedthrough_hpins boundary_optimize_invert_hpins bus clock_gating_exclude_signal constant cts_isolated cts_isolated_effective depth dft_constant_value dft_controllable dft_dedicated_wrapper_reason dft_driven_by_clock dft_partition direction dont_touch dont_touch_effective dont_touch_file dont_touch_sources edge escaped_name exceptions hdl_vname hinst hnet hport is_booth_encoded is_boundary_duplicate is_boundary_feedback is_boundary_feedthru is_boundary_phase_inverted is_initial_phase_inverted is_phase_inverted layer location lp_asserted_probability lp_asserted_toggle_rate lp_system_asserted_probability lp_system_asserted_toggle_rate lssd_master_clock name net num_exceptions obj_type original_name partition_pin place_status prune_unused_logic safety_dcls_isolate_pin safety_dmr_error_signal_endpoint side timing_constant timing_constant_source width wrapper_control wrapper_segment wrapper_type"
setPreference attribute_summary_hnet "base_name connections constant dft_constant_value dont_touch dont_touch_file drivers escaped_name hinst loads lp_asserted_probability lp_asserted_toggle_rate name net num_drivers num_loads obj_type timing_constant timing_constant_source"
setPreference attribute_summary_what_if_wire "layer net obj_type rect width"
setPreference attribute_summary_library_set "aocv_files libraries library_files name obj_type si_files socv_files"
setPreference attribute_summary_actual_scan_segment "active base_name clock clock_edge clock_gating_shift_enable connected_scan_clock_a connected_scan_clock_b connected_shift_enable core_wrapper core_wrapper_type core_wrapper_usage ctl_defined dft_exclude_abstract_segment_from_los_pipeline dft_hookup_pin_sdi dft_hookup_pin_sdo dft_part_of_segment dft_partition dft_scan_chain dft_tail_test_clock dft_tail_test_clock_edge dft_tail_test_clock_waveform_edge dft_test_clock dft_test_clock_edge dft_test_clock_waveform_edge elements escaped_name head_skew_safe instance name obj_type other_clocks power_domain reg_count reorderable scan_in scan_out shift_enable skew_safe tail_clock tail_clock_edge type"
setPreference attribute_summary_density_shape "density obj_type rect"
setPreference attribute_summary_track_pattern "direction layers mask num_tracks obj_type route_rule start step width"
setPreference attribute_summary_lib_arc "aocv_weight base_name from_lib_pin full_name has_bti_aging has_ccs_noise has_hci_aging has_mis_fall has_mis_rise has_socv is_disabled lib_cell mode name obj_type output_signal_level_high output_signal_level_low sdf_cond sense timing_type to_lib_pin when when_end when_library_string when_start"
setPreference attribute_summary_power_domain "available_supply_nets base_domains group is_always_on is_default is_virtual name power_switch_rule_name primary_ground_net primary_power_net shutoff_condition "
setPreference attribute_summary_patch_wire "has_trim_metal is_pin_probe layer location mask net obj_type rect route_rule status trim_metal_color trim_metal_rect"
setPreference attribute_summary_antenna_data "area layer model obj_type ratio type"
setPreference attribute_summary_module "allow_ilm_eco arch_filename arch_name base_name boundary_optimize_constant_hpins boundary_optimize_equal_opposite_hpins boundary_optimize_feedthrough_hpins boundary_optimize_invert_hpins boundary_opto clock_gating_auto_path_adjust clock_gating_auto_path_adjust_fixed_delay clock_gating_auto_path_adjust_multiplier clock_gating_exclude clock_gating_hierarchical clock_gating_max_flops clock_gating_min_flops clock_gating_module clock_gating_test_signal control_logic_optimization delete_unloaded_insts delete_unloaded_seqs design design_verification_effort dft_dont_scan dont_touch dont_touch_file dont_touch_hports dont_use_cells dont_use_cells_effective dp_csa dp_csa_factorize dp_opt_power_opt dp_rename dp_sharing dp_speculation embedded_script entity_filename entity_name has_dp_rewrite_gint has_dp_shared_gint hdl_all_filelist hdl_config_name hdl_cw_list hdl_elab_command_params hdl_filelist hdl_parameters hdl_pipeline_comp hdl_user_name hdl_vdp_list hinsts incrsyn_force_not_replace is_ilm is_retimed language library_name logical_hier lp_clock_gating_test_signal minimize_uniquify multibit_allow_async_phase_map name obj_type opt_retime_move_mux_loop_with_register pbs_mim_keep_folded retime retime_hard_region retime_period_percentage retime_ssw_sync_enable speed_grade sub_arch ungroup_ok use_cells user_speed_grade user_sub_arch"
setPreference attribute_summary_port_bus "base_name bits design direction escaped_name lsb msb name obj_type"
setPreference attribute_summary_formal_verification_constraint "base_name escaped_name name obj_type"
setPreference attribute_summary_wire "begin_extension direction end_extension layer length mask net obj_type points rect route_rule status width"
setPreference attribute_summary_bus_guide "area bottom_layer net_group obj_type rect top_layer type"

