###############################################################
#  Generated by:      Cadence Innovus 25.13-s088_1
#  OS:                Linux x86_64(Host ID vlsi.iitgn.ac.in)
#  Generated on:      Mon Jun  1 15:34:33 2026
#  Design:            riscv_top
#  Command:           create_ccopt_clock_tree_spec -file ../reports/ccopt_spec.tcl
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk_i true

# Clocks present at pin clk_i
#   clk (period 50.000ns) in timing_config CON([../synth/outputs/riscv_top_synth.sdc])
create_ccopt_clock_tree -name clk -source clk_i -no_skew_group
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk_i 50

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:clk in timing_config:CON (sdc ../synth/outputs/riscv_top_synth.sdc)
create_ccopt_skew_group -name clk/CON -sources clk_i -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/CON true
set_ccopt_property extracted_from_clock_name -skew_group clk/CON clk
set_ccopt_property extracted_from_constraint_mode_names -skew_group clk/CON {CON  }
set_ccopt_property extracted_from_delay_corners -skew_group clk/CON {WC_CORNER BC_CORNER}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

