
//input ports
add mapped point clk_i clk_i -type PI PI
add mapped point rst_ni rst_ni -type PI PI
add mapped point rs1_addr_i[4] rs1_addr_i[4] -type PI PI
add mapped point rs1_addr_i[3] rs1_addr_i[3] -type PI PI
add mapped point rs1_addr_i[2] rs1_addr_i[2] -type PI PI
add mapped point rs1_addr_i[1] rs1_addr_i[1] -type PI PI
add mapped point rs1_addr_i[0] rs1_addr_i[0] -type PI PI
add mapped point rs2_addr_i[4] rs2_addr_i[4] -type PI PI
add mapped point rs2_addr_i[3] rs2_addr_i[3] -type PI PI
add mapped point rs2_addr_i[2] rs2_addr_i[2] -type PI PI
add mapped point rs2_addr_i[1] rs2_addr_i[1] -type PI PI
add mapped point rs2_addr_i[0] rs2_addr_i[0] -type PI PI
add mapped point rd_addr_i[4] rd_addr_i[4] -type PI PI
add mapped point rd_addr_i[3] rd_addr_i[3] -type PI PI
add mapped point rd_addr_i[2] rd_addr_i[2] -type PI PI
add mapped point rd_addr_i[1] rd_addr_i[1] -type PI PI
add mapped point rd_addr_i[0] rd_addr_i[0] -type PI PI
add mapped point we_i we_i -type PI PI
add mapped point imm_i[31] imm_i[31] -type PI PI
add mapped point imm_i[30] imm_i[30] -type PI PI
add mapped point imm_i[29] imm_i[29] -type PI PI
add mapped point imm_i[28] imm_i[28] -type PI PI
add mapped point imm_i[27] imm_i[27] -type PI PI
add mapped point imm_i[26] imm_i[26] -type PI PI
add mapped point imm_i[25] imm_i[25] -type PI PI
add mapped point imm_i[24] imm_i[24] -type PI PI
add mapped point imm_i[23] imm_i[23] -type PI PI
add mapped point imm_i[22] imm_i[22] -type PI PI
add mapped point imm_i[21] imm_i[21] -type PI PI
add mapped point imm_i[20] imm_i[20] -type PI PI
add mapped point imm_i[19] imm_i[19] -type PI PI
add mapped point imm_i[18] imm_i[18] -type PI PI
add mapped point imm_i[17] imm_i[17] -type PI PI
add mapped point imm_i[16] imm_i[16] -type PI PI
add mapped point imm_i[15] imm_i[15] -type PI PI
add mapped point imm_i[14] imm_i[14] -type PI PI
add mapped point imm_i[13] imm_i[13] -type PI PI
add mapped point imm_i[12] imm_i[12] -type PI PI
add mapped point imm_i[11] imm_i[11] -type PI PI
add mapped point imm_i[10] imm_i[10] -type PI PI
add mapped point imm_i[9] imm_i[9] -type PI PI
add mapped point imm_i[8] imm_i[8] -type PI PI
add mapped point imm_i[7] imm_i[7] -type PI PI
add mapped point imm_i[6] imm_i[6] -type PI PI
add mapped point imm_i[5] imm_i[5] -type PI PI
add mapped point imm_i[4] imm_i[4] -type PI PI
add mapped point imm_i[3] imm_i[3] -type PI PI
add mapped point imm_i[2] imm_i[2] -type PI PI
add mapped point imm_i[1] imm_i[1] -type PI PI
add mapped point imm_i[0] imm_i[0] -type PI PI
add mapped point alu_src_b_i alu_src_b_i -type PI PI
add mapped point alu_op_i[3] alu_op_i[3] -type PI PI
add mapped point alu_op_i[2] alu_op_i[2] -type PI PI
add mapped point alu_op_i[1] alu_op_i[1] -type PI PI
add mapped point alu_op_i[0] alu_op_i[0] -type PI PI
add mapped point dbg_addr_i[4] dbg_addr_i[4] -type PI PI
add mapped point dbg_addr_i[3] dbg_addr_i[3] -type PI PI
add mapped point dbg_addr_i[2] dbg_addr_i[2] -type PI PI
add mapped point dbg_addr_i[1] dbg_addr_i[1] -type PI PI
add mapped point dbg_addr_i[0] dbg_addr_i[0] -type PI PI

//output ports
add mapped point alu_result_o[31] alu_result_o[31] -type PO PO
add mapped point alu_result_o[30] alu_result_o[30] -type PO PO
add mapped point alu_result_o[29] alu_result_o[29] -type PO PO
add mapped point alu_result_o[28] alu_result_o[28] -type PO PO
add mapped point alu_result_o[27] alu_result_o[27] -type PO PO
add mapped point alu_result_o[26] alu_result_o[26] -type PO PO
add mapped point alu_result_o[25] alu_result_o[25] -type PO PO
add mapped point alu_result_o[24] alu_result_o[24] -type PO PO
add mapped point alu_result_o[23] alu_result_o[23] -type PO PO
add mapped point alu_result_o[22] alu_result_o[22] -type PO PO
add mapped point alu_result_o[21] alu_result_o[21] -type PO PO
add mapped point alu_result_o[20] alu_result_o[20] -type PO PO
add mapped point alu_result_o[19] alu_result_o[19] -type PO PO
add mapped point alu_result_o[18] alu_result_o[18] -type PO PO
add mapped point alu_result_o[17] alu_result_o[17] -type PO PO
add mapped point alu_result_o[16] alu_result_o[16] -type PO PO
add mapped point alu_result_o[15] alu_result_o[15] -type PO PO
add mapped point alu_result_o[14] alu_result_o[14] -type PO PO
add mapped point alu_result_o[13] alu_result_o[13] -type PO PO
add mapped point alu_result_o[12] alu_result_o[12] -type PO PO
add mapped point alu_result_o[11] alu_result_o[11] -type PO PO
add mapped point alu_result_o[10] alu_result_o[10] -type PO PO
add mapped point alu_result_o[9] alu_result_o[9] -type PO PO
add mapped point alu_result_o[8] alu_result_o[8] -type PO PO
add mapped point alu_result_o[7] alu_result_o[7] -type PO PO
add mapped point alu_result_o[6] alu_result_o[6] -type PO PO
add mapped point alu_result_o[5] alu_result_o[5] -type PO PO
add mapped point alu_result_o[4] alu_result_o[4] -type PO PO
add mapped point alu_result_o[3] alu_result_o[3] -type PO PO
add mapped point alu_result_o[2] alu_result_o[2] -type PO PO
add mapped point alu_result_o[1] alu_result_o[1] -type PO PO
add mapped point alu_result_o[0] alu_result_o[0] -type PO PO
add mapped point zero_o zero_o -type PO PO
add mapped point neg_o neg_o -type PO PO
add mapped point overflow_o overflow_o -type PO PO
add mapped point carry_o carry_o -type PO PO
add mapped point dbg_data_o[31] dbg_data_o[31] -type PO PO
add mapped point dbg_data_o[30] dbg_data_o[30] -type PO PO
add mapped point dbg_data_o[29] dbg_data_o[29] -type PO PO
add mapped point dbg_data_o[28] dbg_data_o[28] -type PO PO
add mapped point dbg_data_o[27] dbg_data_o[27] -type PO PO
add mapped point dbg_data_o[26] dbg_data_o[26] -type PO PO
add mapped point dbg_data_o[25] dbg_data_o[25] -type PO PO
add mapped point dbg_data_o[24] dbg_data_o[24] -type PO PO
add mapped point dbg_data_o[23] dbg_data_o[23] -type PO PO
add mapped point dbg_data_o[22] dbg_data_o[22] -type PO PO
add mapped point dbg_data_o[21] dbg_data_o[21] -type PO PO
add mapped point dbg_data_o[20] dbg_data_o[20] -type PO PO
add mapped point dbg_data_o[19] dbg_data_o[19] -type PO PO
add mapped point dbg_data_o[18] dbg_data_o[18] -type PO PO
add mapped point dbg_data_o[17] dbg_data_o[17] -type PO PO
add mapped point dbg_data_o[16] dbg_data_o[16] -type PO PO
add mapped point dbg_data_o[15] dbg_data_o[15] -type PO PO
add mapped point dbg_data_o[14] dbg_data_o[14] -type PO PO
add mapped point dbg_data_o[13] dbg_data_o[13] -type PO PO
add mapped point dbg_data_o[12] dbg_data_o[12] -type PO PO
add mapped point dbg_data_o[11] dbg_data_o[11] -type PO PO
add mapped point dbg_data_o[10] dbg_data_o[10] -type PO PO
add mapped point dbg_data_o[9] dbg_data_o[9] -type PO PO
add mapped point dbg_data_o[8] dbg_data_o[8] -type PO PO
add mapped point dbg_data_o[7] dbg_data_o[7] -type PO PO
add mapped point dbg_data_o[6] dbg_data_o[6] -type PO PO
add mapped point dbg_data_o[5] dbg_data_o[5] -type PO PO
add mapped point dbg_data_o[4] dbg_data_o[4] -type PO PO
add mapped point dbg_data_o[3] dbg_data_o[3] -type PO PO
add mapped point dbg_data_o[2] dbg_data_o[2] -type PO PO
add mapped point dbg_data_o[1] dbg_data_o[1] -type PO PO
add mapped point dbg_data_o[0] dbg_data_o[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point u_rf/regs[1][0]/q u_rf/regs_reg[1][0]/Q -type DFF DFF
add mapped point u_rf/regs[1][1]/q u_rf/regs_reg[1][1]/Q -type DFF DFF
add mapped point u_rf/regs[1][2]/q u_rf/regs_reg[1][2]/Q -type DFF DFF
add mapped point u_rf/regs[1][3]/q u_rf/regs_reg[1][3]/Q -type DFF DFF
add mapped point u_rf/regs[1][4]/q u_rf/regs_reg[1][4]/Q -type DFF DFF
add mapped point u_rf/regs[1][5]/q u_rf/regs_reg[1][5]/Q -type DFF DFF
add mapped point u_rf/regs[1][6]/q u_rf/regs_reg[1][6]/Q -type DFF DFF
add mapped point u_rf/regs[1][7]/q u_rf/regs_reg[1][7]/Q -type DFF DFF
add mapped point u_rf/regs[1][8]/q u_rf/regs_reg[1][8]/Q -type DFF DFF
add mapped point u_rf/regs[1][9]/q u_rf/regs_reg[1][9]/Q -type DFF DFF
add mapped point u_rf/regs[1][10]/q u_rf/regs_reg[1][10]/Q -type DFF DFF
add mapped point u_rf/regs[1][11]/q u_rf/regs_reg[1][11]/Q -type DFF DFF
add mapped point u_rf/regs[1][12]/q u_rf/regs_reg[1][12]/Q -type DFF DFF
add mapped point u_rf/regs[1][13]/q u_rf/regs_reg[1][13]/Q -type DFF DFF
add mapped point u_rf/regs[1][14]/q u_rf/regs_reg[1][14]/Q -type DFF DFF
add mapped point u_rf/regs[1][15]/q u_rf/regs_reg[1][15]/Q -type DFF DFF
add mapped point u_rf/regs[1][16]/q u_rf/regs_reg[1][16]/Q -type DFF DFF
add mapped point u_rf/regs[1][17]/q u_rf/regs_reg[1][17]/Q -type DFF DFF
add mapped point u_rf/regs[1][18]/q u_rf/regs_reg[1][18]/Q -type DFF DFF
add mapped point u_rf/regs[1][19]/q u_rf/regs_reg[1][19]/Q -type DFF DFF
add mapped point u_rf/regs[1][20]/q u_rf/regs_reg[1][20]/Q -type DFF DFF
add mapped point u_rf/regs[1][21]/q u_rf/regs_reg[1][21]/Q -type DFF DFF
add mapped point u_rf/regs[1][22]/q u_rf/regs_reg[1][22]/Q -type DFF DFF
add mapped point u_rf/regs[1][23]/q u_rf/regs_reg[1][23]/Q -type DFF DFF
add mapped point u_rf/regs[1][24]/q u_rf/regs_reg[1][24]/Q -type DFF DFF
add mapped point u_rf/regs[1][25]/q u_rf/regs_reg[1][25]/Q -type DFF DFF
add mapped point u_rf/regs[1][26]/q u_rf/regs_reg[1][26]/Q -type DFF DFF
add mapped point u_rf/regs[1][27]/q u_rf/regs_reg[1][27]/Q -type DFF DFF
add mapped point u_rf/regs[1][28]/q u_rf/regs_reg[1][28]/Q -type DFF DFF
add mapped point u_rf/regs[1][29]/q u_rf/regs_reg[1][29]/Q -type DFF DFF
add mapped point u_rf/regs[1][30]/q u_rf/regs_reg[1][30]/Q -type DFF DFF
add mapped point u_rf/regs[1][31]/q u_rf/regs_reg[1][31]/Q -type DFF DFF
add mapped point u_rf/regs[2][0]/q u_rf/regs_reg[2][0]/Q -type DFF DFF
add mapped point u_rf/regs[2][1]/q u_rf/regs_reg[2][1]/Q -type DFF DFF
add mapped point u_rf/regs[2][2]/q u_rf/regs_reg[2][2]/Q -type DFF DFF
add mapped point u_rf/regs[2][3]/q u_rf/regs_reg[2][3]/Q -type DFF DFF
add mapped point u_rf/regs[2][4]/q u_rf/regs_reg[2][4]/Q -type DFF DFF
add mapped point u_rf/regs[2][5]/q u_rf/regs_reg[2][5]/Q -type DFF DFF
add mapped point u_rf/regs[2][6]/q u_rf/regs_reg[2][6]/Q -type DFF DFF
add mapped point u_rf/regs[2][7]/q u_rf/regs_reg[2][7]/Q -type DFF DFF
add mapped point u_rf/regs[2][8]/q u_rf/regs_reg[2][8]/Q -type DFF DFF
add mapped point u_rf/regs[2][9]/q u_rf/regs_reg[2][9]/Q -type DFF DFF
add mapped point u_rf/regs[2][10]/q u_rf/regs_reg[2][10]/Q -type DFF DFF
add mapped point u_rf/regs[2][11]/q u_rf/regs_reg[2][11]/Q -type DFF DFF
add mapped point u_rf/regs[2][12]/q u_rf/regs_reg[2][12]/Q -type DFF DFF
add mapped point u_rf/regs[2][13]/q u_rf/regs_reg[2][13]/Q -type DFF DFF
add mapped point u_rf/regs[2][14]/q u_rf/regs_reg[2][14]/Q -type DFF DFF
add mapped point u_rf/regs[2][15]/q u_rf/regs_reg[2][15]/Q -type DFF DFF
add mapped point u_rf/regs[2][16]/q u_rf/regs_reg[2][16]/Q -type DFF DFF
add mapped point u_rf/regs[2][17]/q u_rf/regs_reg[2][17]/Q -type DFF DFF
add mapped point u_rf/regs[2][18]/q u_rf/regs_reg[2][18]/Q -type DFF DFF
add mapped point u_rf/regs[2][19]/q u_rf/regs_reg[2][19]/Q -type DFF DFF
add mapped point u_rf/regs[2][20]/q u_rf/regs_reg[2][20]/Q -type DFF DFF
add mapped point u_rf/regs[2][21]/q u_rf/regs_reg[2][21]/Q -type DFF DFF
add mapped point u_rf/regs[2][22]/q u_rf/regs_reg[2][22]/Q -type DFF DFF
add mapped point u_rf/regs[2][23]/q u_rf/regs_reg[2][23]/Q -type DFF DFF
add mapped point u_rf/regs[2][24]/q u_rf/regs_reg[2][24]/Q -type DFF DFF
add mapped point u_rf/regs[2][25]/q u_rf/regs_reg[2][25]/Q -type DFF DFF
add mapped point u_rf/regs[2][26]/q u_rf/regs_reg[2][26]/Q -type DFF DFF
add mapped point u_rf/regs[2][27]/q u_rf/regs_reg[2][27]/Q -type DFF DFF
add mapped point u_rf/regs[2][28]/q u_rf/regs_reg[2][28]/Q -type DFF DFF
add mapped point u_rf/regs[2][29]/q u_rf/regs_reg[2][29]/Q -type DFF DFF
add mapped point u_rf/regs[2][30]/q u_rf/regs_reg[2][30]/Q -type DFF DFF
add mapped point u_rf/regs[2][31]/q u_rf/regs_reg[2][31]/Q -type DFF DFF
add mapped point u_rf/regs[3][0]/q u_rf/regs_reg[3][0]/Q -type DFF DFF
add mapped point u_rf/regs[3][1]/q u_rf/regs_reg[3][1]/Q -type DFF DFF
add mapped point u_rf/regs[3][2]/q u_rf/regs_reg[3][2]/Q -type DFF DFF
add mapped point u_rf/regs[3][3]/q u_rf/regs_reg[3][3]/Q -type DFF DFF
add mapped point u_rf/regs[3][4]/q u_rf/regs_reg[3][4]/Q -type DFF DFF
add mapped point u_rf/regs[3][5]/q u_rf/regs_reg[3][5]/Q -type DFF DFF
add mapped point u_rf/regs[3][6]/q u_rf/regs_reg[3][6]/Q -type DFF DFF
add mapped point u_rf/regs[3][7]/q u_rf/regs_reg[3][7]/Q -type DFF DFF
add mapped point u_rf/regs[3][8]/q u_rf/regs_reg[3][8]/Q -type DFF DFF
add mapped point u_rf/regs[3][9]/q u_rf/regs_reg[3][9]/Q -type DFF DFF
add mapped point u_rf/regs[3][10]/q u_rf/regs_reg[3][10]/Q -type DFF DFF
add mapped point u_rf/regs[3][11]/q u_rf/regs_reg[3][11]/Q -type DFF DFF
add mapped point u_rf/regs[3][12]/q u_rf/regs_reg[3][12]/Q -type DFF DFF
add mapped point u_rf/regs[3][13]/q u_rf/regs_reg[3][13]/Q -type DFF DFF
add mapped point u_rf/regs[3][14]/q u_rf/regs_reg[3][14]/Q -type DFF DFF
add mapped point u_rf/regs[3][15]/q u_rf/regs_reg[3][15]/Q -type DFF DFF
add mapped point u_rf/regs[3][16]/q u_rf/regs_reg[3][16]/Q -type DFF DFF
add mapped point u_rf/regs[3][17]/q u_rf/regs_reg[3][17]/Q -type DFF DFF
add mapped point u_rf/regs[3][18]/q u_rf/regs_reg[3][18]/Q -type DFF DFF
add mapped point u_rf/regs[3][19]/q u_rf/regs_reg[3][19]/Q -type DFF DFF
add mapped point u_rf/regs[3][20]/q u_rf/regs_reg[3][20]/Q -type DFF DFF
add mapped point u_rf/regs[3][21]/q u_rf/regs_reg[3][21]/Q -type DFF DFF
add mapped point u_rf/regs[3][22]/q u_rf/regs_reg[3][22]/Q -type DFF DFF
add mapped point u_rf/regs[3][23]/q u_rf/regs_reg[3][23]/Q -type DFF DFF
add mapped point u_rf/regs[3][24]/q u_rf/regs_reg[3][24]/Q -type DFF DFF
add mapped point u_rf/regs[3][25]/q u_rf/regs_reg[3][25]/Q -type DFF DFF
add mapped point u_rf/regs[3][26]/q u_rf/regs_reg[3][26]/Q -type DFF DFF
add mapped point u_rf/regs[3][27]/q u_rf/regs_reg[3][27]/Q -type DFF DFF
add mapped point u_rf/regs[3][28]/q u_rf/regs_reg[3][28]/Q -type DFF DFF
add mapped point u_rf/regs[3][29]/q u_rf/regs_reg[3][29]/Q -type DFF DFF
add mapped point u_rf/regs[3][30]/q u_rf/regs_reg[3][30]/Q -type DFF DFF
add mapped point u_rf/regs[3][31]/q u_rf/regs_reg[3][31]/Q -type DFF DFF
add mapped point u_rf/regs[4][0]/q u_rf/regs_reg[4][0]/Q -type DFF DFF
add mapped point u_rf/regs[4][1]/q u_rf/regs_reg[4][1]/Q -type DFF DFF
add mapped point u_rf/regs[4][2]/q u_rf/regs_reg[4][2]/Q -type DFF DFF
add mapped point u_rf/regs[4][3]/q u_rf/regs_reg[4][3]/Q -type DFF DFF
add mapped point u_rf/regs[4][4]/q u_rf/regs_reg[4][4]/Q -type DFF DFF
add mapped point u_rf/regs[4][5]/q u_rf/regs_reg[4][5]/Q -type DFF DFF
add mapped point u_rf/regs[4][6]/q u_rf/regs_reg[4][6]/Q -type DFF DFF
add mapped point u_rf/regs[4][7]/q u_rf/regs_reg[4][7]/Q -type DFF DFF
add mapped point u_rf/regs[4][8]/q u_rf/regs_reg[4][8]/Q -type DFF DFF
add mapped point u_rf/regs[4][9]/q u_rf/regs_reg[4][9]/Q -type DFF DFF
add mapped point u_rf/regs[4][10]/q u_rf/regs_reg[4][10]/Q -type DFF DFF
add mapped point u_rf/regs[4][11]/q u_rf/regs_reg[4][11]/Q -type DFF DFF
add mapped point u_rf/regs[4][12]/q u_rf/regs_reg[4][12]/Q -type DFF DFF
add mapped point u_rf/regs[4][13]/q u_rf/regs_reg[4][13]/Q -type DFF DFF
add mapped point u_rf/regs[4][14]/q u_rf/regs_reg[4][14]/Q -type DFF DFF
add mapped point u_rf/regs[4][15]/q u_rf/regs_reg[4][15]/Q -type DFF DFF
add mapped point u_rf/regs[4][16]/q u_rf/regs_reg[4][16]/Q -type DFF DFF
add mapped point u_rf/regs[4][17]/q u_rf/regs_reg[4][17]/Q -type DFF DFF
add mapped point u_rf/regs[4][18]/q u_rf/regs_reg[4][18]/Q -type DFF DFF
add mapped point u_rf/regs[4][19]/q u_rf/regs_reg[4][19]/Q -type DFF DFF
add mapped point u_rf/regs[4][20]/q u_rf/regs_reg[4][20]/Q -type DFF DFF
add mapped point u_rf/regs[4][21]/q u_rf/regs_reg[4][21]/Q -type DFF DFF
add mapped point u_rf/regs[4][22]/q u_rf/regs_reg[4][22]/Q -type DFF DFF
add mapped point u_rf/regs[4][23]/q u_rf/regs_reg[4][23]/Q -type DFF DFF
add mapped point u_rf/regs[4][24]/q u_rf/regs_reg[4][24]/Q -type DFF DFF
add mapped point u_rf/regs[4][25]/q u_rf/regs_reg[4][25]/Q -type DFF DFF
add mapped point u_rf/regs[4][26]/q u_rf/regs_reg[4][26]/Q -type DFF DFF
add mapped point u_rf/regs[4][27]/q u_rf/regs_reg[4][27]/Q -type DFF DFF
add mapped point u_rf/regs[4][28]/q u_rf/regs_reg[4][28]/Q -type DFF DFF
add mapped point u_rf/regs[4][29]/q u_rf/regs_reg[4][29]/Q -type DFF DFF
add mapped point u_rf/regs[4][30]/q u_rf/regs_reg[4][30]/Q -type DFF DFF
add mapped point u_rf/regs[4][31]/q u_rf/regs_reg[4][31]/Q -type DFF DFF
add mapped point u_rf/regs[5][0]/q u_rf/regs_reg[5][0]/Q -type DFF DFF
add mapped point u_rf/regs[5][1]/q u_rf/regs_reg[5][1]/Q -type DFF DFF
add mapped point u_rf/regs[5][2]/q u_rf/regs_reg[5][2]/Q -type DFF DFF
add mapped point u_rf/regs[5][3]/q u_rf/regs_reg[5][3]/Q -type DFF DFF
add mapped point u_rf/regs[5][4]/q u_rf/regs_reg[5][4]/Q -type DFF DFF
add mapped point u_rf/regs[5][5]/q u_rf/regs_reg[5][5]/Q -type DFF DFF
add mapped point u_rf/regs[5][6]/q u_rf/regs_reg[5][6]/Q -type DFF DFF
add mapped point u_rf/regs[5][7]/q u_rf/regs_reg[5][7]/Q -type DFF DFF
add mapped point u_rf/regs[5][8]/q u_rf/regs_reg[5][8]/Q -type DFF DFF
add mapped point u_rf/regs[5][9]/q u_rf/regs_reg[5][9]/Q -type DFF DFF
add mapped point u_rf/regs[5][10]/q u_rf/regs_reg[5][10]/Q -type DFF DFF
add mapped point u_rf/regs[5][11]/q u_rf/regs_reg[5][11]/Q -type DFF DFF
add mapped point u_rf/regs[5][12]/q u_rf/regs_reg[5][12]/Q -type DFF DFF
add mapped point u_rf/regs[5][13]/q u_rf/regs_reg[5][13]/Q -type DFF DFF
add mapped point u_rf/regs[5][14]/q u_rf/regs_reg[5][14]/Q -type DFF DFF
add mapped point u_rf/regs[5][15]/q u_rf/regs_reg[5][15]/Q -type DFF DFF
add mapped point u_rf/regs[5][16]/q u_rf/regs_reg[5][16]/Q -type DFF DFF
add mapped point u_rf/regs[5][17]/q u_rf/regs_reg[5][17]/Q -type DFF DFF
add mapped point u_rf/regs[5][18]/q u_rf/regs_reg[5][18]/Q -type DFF DFF
add mapped point u_rf/regs[5][19]/q u_rf/regs_reg[5][19]/Q -type DFF DFF
add mapped point u_rf/regs[5][20]/q u_rf/regs_reg[5][20]/Q -type DFF DFF
add mapped point u_rf/regs[5][21]/q u_rf/regs_reg[5][21]/Q -type DFF DFF
add mapped point u_rf/regs[5][22]/q u_rf/regs_reg[5][22]/Q -type DFF DFF
add mapped point u_rf/regs[5][23]/q u_rf/regs_reg[5][23]/Q -type DFF DFF
add mapped point u_rf/regs[5][24]/q u_rf/regs_reg[5][24]/Q -type DFF DFF
add mapped point u_rf/regs[5][25]/q u_rf/regs_reg[5][25]/Q -type DFF DFF
add mapped point u_rf/regs[5][26]/q u_rf/regs_reg[5][26]/Q -type DFF DFF
add mapped point u_rf/regs[5][27]/q u_rf/regs_reg[5][27]/Q -type DFF DFF
add mapped point u_rf/regs[5][28]/q u_rf/regs_reg[5][28]/Q -type DFF DFF
add mapped point u_rf/regs[5][29]/q u_rf/regs_reg[5][29]/Q -type DFF DFF
add mapped point u_rf/regs[5][30]/q u_rf/regs_reg[5][30]/Q -type DFF DFF
add mapped point u_rf/regs[5][31]/q u_rf/regs_reg[5][31]/Q -type DFF DFF
add mapped point u_rf/regs[6][0]/q u_rf/regs_reg[6][0]/Q -type DFF DFF
add mapped point u_rf/regs[6][1]/q u_rf/regs_reg[6][1]/Q -type DFF DFF
add mapped point u_rf/regs[6][2]/q u_rf/regs_reg[6][2]/Q -type DFF DFF
add mapped point u_rf/regs[6][3]/q u_rf/regs_reg[6][3]/Q -type DFF DFF
add mapped point u_rf/regs[6][4]/q u_rf/regs_reg[6][4]/Q -type DFF DFF
add mapped point u_rf/regs[6][5]/q u_rf/regs_reg[6][5]/Q -type DFF DFF
add mapped point u_rf/regs[6][6]/q u_rf/regs_reg[6][6]/Q -type DFF DFF
add mapped point u_rf/regs[6][7]/q u_rf/regs_reg[6][7]/Q -type DFF DFF
add mapped point u_rf/regs[6][8]/q u_rf/regs_reg[6][8]/Q -type DFF DFF
add mapped point u_rf/regs[6][9]/q u_rf/regs_reg[6][9]/Q -type DFF DFF
add mapped point u_rf/regs[6][10]/q u_rf/regs_reg[6][10]/Q -type DFF DFF
add mapped point u_rf/regs[6][11]/q u_rf/regs_reg[6][11]/Q -type DFF DFF
add mapped point u_rf/regs[6][12]/q u_rf/regs_reg[6][12]/Q -type DFF DFF
add mapped point u_rf/regs[6][13]/q u_rf/regs_reg[6][13]/Q -type DFF DFF
add mapped point u_rf/regs[6][14]/q u_rf/regs_reg[6][14]/Q -type DFF DFF
add mapped point u_rf/regs[6][15]/q u_rf/regs_reg[6][15]/Q -type DFF DFF
add mapped point u_rf/regs[6][16]/q u_rf/regs_reg[6][16]/Q -type DFF DFF
add mapped point u_rf/regs[6][17]/q u_rf/regs_reg[6][17]/Q -type DFF DFF
add mapped point u_rf/regs[6][18]/q u_rf/regs_reg[6][18]/Q -type DFF DFF
add mapped point u_rf/regs[6][19]/q u_rf/regs_reg[6][19]/Q -type DFF DFF
add mapped point u_rf/regs[6][20]/q u_rf/regs_reg[6][20]/Q -type DFF DFF
add mapped point u_rf/regs[6][21]/q u_rf/regs_reg[6][21]/Q -type DFF DFF
add mapped point u_rf/regs[6][22]/q u_rf/regs_reg[6][22]/Q -type DFF DFF
add mapped point u_rf/regs[6][23]/q u_rf/regs_reg[6][23]/Q -type DFF DFF
add mapped point u_rf/regs[6][24]/q u_rf/regs_reg[6][24]/Q -type DFF DFF
add mapped point u_rf/regs[6][25]/q u_rf/regs_reg[6][25]/Q -type DFF DFF
add mapped point u_rf/regs[6][26]/q u_rf/regs_reg[6][26]/Q -type DFF DFF
add mapped point u_rf/regs[6][27]/q u_rf/regs_reg[6][27]/Q -type DFF DFF
add mapped point u_rf/regs[6][28]/q u_rf/regs_reg[6][28]/Q -type DFF DFF
add mapped point u_rf/regs[6][29]/q u_rf/regs_reg[6][29]/Q -type DFF DFF
add mapped point u_rf/regs[6][30]/q u_rf/regs_reg[6][30]/Q -type DFF DFF
add mapped point u_rf/regs[6][31]/q u_rf/regs_reg[6][31]/Q -type DFF DFF
add mapped point u_rf/regs[7][0]/q u_rf/regs_reg[7][0]/Q -type DFF DFF
add mapped point u_rf/regs[7][1]/q u_rf/regs_reg[7][1]/Q -type DFF DFF
add mapped point u_rf/regs[7][2]/q u_rf/regs_reg[7][2]/Q -type DFF DFF
add mapped point u_rf/regs[7][3]/q u_rf/regs_reg[7][3]/Q -type DFF DFF
add mapped point u_rf/regs[7][4]/q u_rf/regs_reg[7][4]/Q -type DFF DFF
add mapped point u_rf/regs[7][5]/q u_rf/regs_reg[7][5]/Q -type DFF DFF
add mapped point u_rf/regs[7][6]/q u_rf/regs_reg[7][6]/Q -type DFF DFF
add mapped point u_rf/regs[7][7]/q u_rf/regs_reg[7][7]/Q -type DFF DFF
add mapped point u_rf/regs[7][8]/q u_rf/regs_reg[7][8]/Q -type DFF DFF
add mapped point u_rf/regs[7][9]/q u_rf/regs_reg[7][9]/Q -type DFF DFF
add mapped point u_rf/regs[7][10]/q u_rf/regs_reg[7][10]/Q -type DFF DFF
add mapped point u_rf/regs[7][11]/q u_rf/regs_reg[7][11]/Q -type DFF DFF
add mapped point u_rf/regs[7][12]/q u_rf/regs_reg[7][12]/Q -type DFF DFF
add mapped point u_rf/regs[7][13]/q u_rf/regs_reg[7][13]/Q -type DFF DFF
add mapped point u_rf/regs[7][14]/q u_rf/regs_reg[7][14]/Q -type DFF DFF
add mapped point u_rf/regs[7][15]/q u_rf/regs_reg[7][15]/Q -type DFF DFF
add mapped point u_rf/regs[7][16]/q u_rf/regs_reg[7][16]/Q -type DFF DFF
add mapped point u_rf/regs[7][17]/q u_rf/regs_reg[7][17]/Q -type DFF DFF
add mapped point u_rf/regs[7][18]/q u_rf/regs_reg[7][18]/Q -type DFF DFF
add mapped point u_rf/regs[7][19]/q u_rf/regs_reg[7][19]/Q -type DFF DFF
add mapped point u_rf/regs[7][20]/q u_rf/regs_reg[7][20]/Q -type DFF DFF
add mapped point u_rf/regs[7][21]/q u_rf/regs_reg[7][21]/Q -type DFF DFF
add mapped point u_rf/regs[7][22]/q u_rf/regs_reg[7][22]/Q -type DFF DFF
add mapped point u_rf/regs[7][23]/q u_rf/regs_reg[7][23]/Q -type DFF DFF
add mapped point u_rf/regs[7][24]/q u_rf/regs_reg[7][24]/Q -type DFF DFF
add mapped point u_rf/regs[7][25]/q u_rf/regs_reg[7][25]/Q -type DFF DFF
add mapped point u_rf/regs[7][26]/q u_rf/regs_reg[7][26]/Q -type DFF DFF
add mapped point u_rf/regs[7][27]/q u_rf/regs_reg[7][27]/Q -type DFF DFF
add mapped point u_rf/regs[7][28]/q u_rf/regs_reg[7][28]/Q -type DFF DFF
add mapped point u_rf/regs[7][29]/q u_rf/regs_reg[7][29]/Q -type DFF DFF
add mapped point u_rf/regs[7][30]/q u_rf/regs_reg[7][30]/Q -type DFF DFF
add mapped point u_rf/regs[7][31]/q u_rf/regs_reg[7][31]/Q -type DFF DFF
add mapped point u_rf/regs[8][0]/q u_rf/regs_reg[8][0]/Q -type DFF DFF
add mapped point u_rf/regs[8][1]/q u_rf/regs_reg[8][1]/Q -type DFF DFF
add mapped point u_rf/regs[8][2]/q u_rf/regs_reg[8][2]/Q -type DFF DFF
add mapped point u_rf/regs[8][3]/q u_rf/regs_reg[8][3]/Q -type DFF DFF
add mapped point u_rf/regs[8][4]/q u_rf/regs_reg[8][4]/Q -type DFF DFF
add mapped point u_rf/regs[8][5]/q u_rf/regs_reg[8][5]/Q -type DFF DFF
add mapped point u_rf/regs[8][6]/q u_rf/regs_reg[8][6]/Q -type DFF DFF
add mapped point u_rf/regs[8][7]/q u_rf/regs_reg[8][7]/Q -type DFF DFF
add mapped point u_rf/regs[8][8]/q u_rf/regs_reg[8][8]/Q -type DFF DFF
add mapped point u_rf/regs[8][9]/q u_rf/regs_reg[8][9]/Q -type DFF DFF
add mapped point u_rf/regs[8][10]/q u_rf/regs_reg[8][10]/Q -type DFF DFF
add mapped point u_rf/regs[8][11]/q u_rf/regs_reg[8][11]/Q -type DFF DFF
add mapped point u_rf/regs[8][12]/q u_rf/regs_reg[8][12]/Q -type DFF DFF
add mapped point u_rf/regs[8][13]/q u_rf/regs_reg[8][13]/Q -type DFF DFF
add mapped point u_rf/regs[8][14]/q u_rf/regs_reg[8][14]/Q -type DFF DFF
add mapped point u_rf/regs[8][15]/q u_rf/regs_reg[8][15]/Q -type DFF DFF
add mapped point u_rf/regs[8][16]/q u_rf/regs_reg[8][16]/Q -type DFF DFF
add mapped point u_rf/regs[8][17]/q u_rf/regs_reg[8][17]/Q -type DFF DFF
add mapped point u_rf/regs[8][18]/q u_rf/regs_reg[8][18]/Q -type DFF DFF
add mapped point u_rf/regs[8][19]/q u_rf/regs_reg[8][19]/Q -type DFF DFF
add mapped point u_rf/regs[8][20]/q u_rf/regs_reg[8][20]/Q -type DFF DFF
add mapped point u_rf/regs[8][21]/q u_rf/regs_reg[8][21]/Q -type DFF DFF
add mapped point u_rf/regs[8][22]/q u_rf/regs_reg[8][22]/Q -type DFF DFF
add mapped point u_rf/regs[8][23]/q u_rf/regs_reg[8][23]/Q -type DFF DFF
add mapped point u_rf/regs[8][24]/q u_rf/regs_reg[8][24]/Q -type DFF DFF
add mapped point u_rf/regs[8][25]/q u_rf/regs_reg[8][25]/Q -type DFF DFF
add mapped point u_rf/regs[8][26]/q u_rf/regs_reg[8][26]/Q -type DFF DFF
add mapped point u_rf/regs[8][27]/q u_rf/regs_reg[8][27]/Q -type DFF DFF
add mapped point u_rf/regs[8][28]/q u_rf/regs_reg[8][28]/Q -type DFF DFF
add mapped point u_rf/regs[8][29]/q u_rf/regs_reg[8][29]/Q -type DFF DFF
add mapped point u_rf/regs[8][30]/q u_rf/regs_reg[8][30]/Q -type DFF DFF
add mapped point u_rf/regs[8][31]/q u_rf/regs_reg[8][31]/Q -type DFF DFF
add mapped point u_rf/regs[9][0]/q u_rf/regs_reg[9][0]/Q -type DFF DFF
add mapped point u_rf/regs[9][1]/q u_rf/regs_reg[9][1]/Q -type DFF DFF
add mapped point u_rf/regs[9][2]/q u_rf/regs_reg[9][2]/Q -type DFF DFF
add mapped point u_rf/regs[9][3]/q u_rf/regs_reg[9][3]/Q -type DFF DFF
add mapped point u_rf/regs[9][4]/q u_rf/regs_reg[9][4]/Q -type DFF DFF
add mapped point u_rf/regs[9][5]/q u_rf/regs_reg[9][5]/Q -type DFF DFF
add mapped point u_rf/regs[9][6]/q u_rf/regs_reg[9][6]/Q -type DFF DFF
add mapped point u_rf/regs[9][7]/q u_rf/regs_reg[9][7]/Q -type DFF DFF
add mapped point u_rf/regs[9][8]/q u_rf/regs_reg[9][8]/Q -type DFF DFF
add mapped point u_rf/regs[9][9]/q u_rf/regs_reg[9][9]/Q -type DFF DFF
add mapped point u_rf/regs[9][10]/q u_rf/regs_reg[9][10]/Q -type DFF DFF
add mapped point u_rf/regs[9][11]/q u_rf/regs_reg[9][11]/Q -type DFF DFF
add mapped point u_rf/regs[9][12]/q u_rf/regs_reg[9][12]/Q -type DFF DFF
add mapped point u_rf/regs[9][13]/q u_rf/regs_reg[9][13]/Q -type DFF DFF
add mapped point u_rf/regs[9][14]/q u_rf/regs_reg[9][14]/Q -type DFF DFF
add mapped point u_rf/regs[9][15]/q u_rf/regs_reg[9][15]/Q -type DFF DFF
add mapped point u_rf/regs[9][16]/q u_rf/regs_reg[9][16]/Q -type DFF DFF
add mapped point u_rf/regs[9][17]/q u_rf/regs_reg[9][17]/Q -type DFF DFF
add mapped point u_rf/regs[9][18]/q u_rf/regs_reg[9][18]/Q -type DFF DFF
add mapped point u_rf/regs[9][19]/q u_rf/regs_reg[9][19]/Q -type DFF DFF
add mapped point u_rf/regs[9][20]/q u_rf/regs_reg[9][20]/Q -type DFF DFF
add mapped point u_rf/regs[9][21]/q u_rf/regs_reg[9][21]/Q -type DFF DFF
add mapped point u_rf/regs[9][22]/q u_rf/regs_reg[9][22]/Q -type DFF DFF
add mapped point u_rf/regs[9][23]/q u_rf/regs_reg[9][23]/Q -type DFF DFF
add mapped point u_rf/regs[9][24]/q u_rf/regs_reg[9][24]/Q -type DFF DFF
add mapped point u_rf/regs[9][25]/q u_rf/regs_reg[9][25]/Q -type DFF DFF
add mapped point u_rf/regs[9][26]/q u_rf/regs_reg[9][26]/Q -type DFF DFF
add mapped point u_rf/regs[9][27]/q u_rf/regs_reg[9][27]/Q -type DFF DFF
add mapped point u_rf/regs[9][28]/q u_rf/regs_reg[9][28]/Q -type DFF DFF
add mapped point u_rf/regs[9][29]/q u_rf/regs_reg[9][29]/Q -type DFF DFF
add mapped point u_rf/regs[9][30]/q u_rf/regs_reg[9][30]/Q -type DFF DFF
add mapped point u_rf/regs[9][31]/q u_rf/regs_reg[9][31]/Q -type DFF DFF
add mapped point u_rf/regs[10][0]/q u_rf/regs_reg[10][0]/Q -type DFF DFF
add mapped point u_rf/regs[10][1]/q u_rf/regs_reg[10][1]/Q -type DFF DFF
add mapped point u_rf/regs[10][2]/q u_rf/regs_reg[10][2]/Q -type DFF DFF
add mapped point u_rf/regs[10][3]/q u_rf/regs_reg[10][3]/Q -type DFF DFF
add mapped point u_rf/regs[10][4]/q u_rf/regs_reg[10][4]/Q -type DFF DFF
add mapped point u_rf/regs[10][5]/q u_rf/regs_reg[10][5]/Q -type DFF DFF
add mapped point u_rf/regs[10][6]/q u_rf/regs_reg[10][6]/Q -type DFF DFF
add mapped point u_rf/regs[10][7]/q u_rf/regs_reg[10][7]/Q -type DFF DFF
add mapped point u_rf/regs[10][8]/q u_rf/regs_reg[10][8]/Q -type DFF DFF
add mapped point u_rf/regs[10][9]/q u_rf/regs_reg[10][9]/Q -type DFF DFF
add mapped point u_rf/regs[10][10]/q u_rf/regs_reg[10][10]/Q -type DFF DFF
add mapped point u_rf/regs[10][11]/q u_rf/regs_reg[10][11]/Q -type DFF DFF
add mapped point u_rf/regs[10][12]/q u_rf/regs_reg[10][12]/Q -type DFF DFF
add mapped point u_rf/regs[10][13]/q u_rf/regs_reg[10][13]/Q -type DFF DFF
add mapped point u_rf/regs[10][14]/q u_rf/regs_reg[10][14]/Q -type DFF DFF
add mapped point u_rf/regs[10][15]/q u_rf/regs_reg[10][15]/Q -type DFF DFF
add mapped point u_rf/regs[10][16]/q u_rf/regs_reg[10][16]/Q -type DFF DFF
add mapped point u_rf/regs[10][17]/q u_rf/regs_reg[10][17]/Q -type DFF DFF
add mapped point u_rf/regs[10][18]/q u_rf/regs_reg[10][18]/Q -type DFF DFF
add mapped point u_rf/regs[10][19]/q u_rf/regs_reg[10][19]/Q -type DFF DFF
add mapped point u_rf/regs[10][20]/q u_rf/regs_reg[10][20]/Q -type DFF DFF
add mapped point u_rf/regs[10][21]/q u_rf/regs_reg[10][21]/Q -type DFF DFF
add mapped point u_rf/regs[10][22]/q u_rf/regs_reg[10][22]/Q -type DFF DFF
add mapped point u_rf/regs[10][23]/q u_rf/regs_reg[10][23]/Q -type DFF DFF
add mapped point u_rf/regs[10][24]/q u_rf/regs_reg[10][24]/Q -type DFF DFF
add mapped point u_rf/regs[10][25]/q u_rf/regs_reg[10][25]/Q -type DFF DFF
add mapped point u_rf/regs[10][26]/q u_rf/regs_reg[10][26]/Q -type DFF DFF
add mapped point u_rf/regs[10][27]/q u_rf/regs_reg[10][27]/Q -type DFF DFF
add mapped point u_rf/regs[10][28]/q u_rf/regs_reg[10][28]/Q -type DFF DFF
add mapped point u_rf/regs[10][29]/q u_rf/regs_reg[10][29]/Q -type DFF DFF
add mapped point u_rf/regs[10][30]/q u_rf/regs_reg[10][30]/Q -type DFF DFF
add mapped point u_rf/regs[10][31]/q u_rf/regs_reg[10][31]/Q -type DFF DFF
add mapped point u_rf/regs[11][0]/q u_rf/regs_reg[11][0]/Q -type DFF DFF
add mapped point u_rf/regs[11][1]/q u_rf/regs_reg[11][1]/Q -type DFF DFF
add mapped point u_rf/regs[11][2]/q u_rf/regs_reg[11][2]/Q -type DFF DFF
add mapped point u_rf/regs[11][3]/q u_rf/regs_reg[11][3]/Q -type DFF DFF
add mapped point u_rf/regs[11][4]/q u_rf/regs_reg[11][4]/Q -type DFF DFF
add mapped point u_rf/regs[11][5]/q u_rf/regs_reg[11][5]/Q -type DFF DFF
add mapped point u_rf/regs[11][6]/q u_rf/regs_reg[11][6]/Q -type DFF DFF
add mapped point u_rf/regs[11][7]/q u_rf/regs_reg[11][7]/Q -type DFF DFF
add mapped point u_rf/regs[11][8]/q u_rf/regs_reg[11][8]/Q -type DFF DFF
add mapped point u_rf/regs[11][9]/q u_rf/regs_reg[11][9]/Q -type DFF DFF
add mapped point u_rf/regs[11][10]/q u_rf/regs_reg[11][10]/Q -type DFF DFF
add mapped point u_rf/regs[11][11]/q u_rf/regs_reg[11][11]/Q -type DFF DFF
add mapped point u_rf/regs[11][12]/q u_rf/regs_reg[11][12]/Q -type DFF DFF
add mapped point u_rf/regs[11][13]/q u_rf/regs_reg[11][13]/Q -type DFF DFF
add mapped point u_rf/regs[11][14]/q u_rf/regs_reg[11][14]/Q -type DFF DFF
add mapped point u_rf/regs[11][15]/q u_rf/regs_reg[11][15]/Q -type DFF DFF
add mapped point u_rf/regs[11][16]/q u_rf/regs_reg[11][16]/Q -type DFF DFF
add mapped point u_rf/regs[11][17]/q u_rf/regs_reg[11][17]/Q -type DFF DFF
add mapped point u_rf/regs[11][18]/q u_rf/regs_reg[11][18]/Q -type DFF DFF
add mapped point u_rf/regs[11][19]/q u_rf/regs_reg[11][19]/Q -type DFF DFF
add mapped point u_rf/regs[11][20]/q u_rf/regs_reg[11][20]/Q -type DFF DFF
add mapped point u_rf/regs[11][21]/q u_rf/regs_reg[11][21]/Q -type DFF DFF
add mapped point u_rf/regs[11][22]/q u_rf/regs_reg[11][22]/Q -type DFF DFF
add mapped point u_rf/regs[11][23]/q u_rf/regs_reg[11][23]/Q -type DFF DFF
add mapped point u_rf/regs[11][24]/q u_rf/regs_reg[11][24]/Q -type DFF DFF
add mapped point u_rf/regs[11][25]/q u_rf/regs_reg[11][25]/Q -type DFF DFF
add mapped point u_rf/regs[11][26]/q u_rf/regs_reg[11][26]/Q -type DFF DFF
add mapped point u_rf/regs[11][27]/q u_rf/regs_reg[11][27]/Q -type DFF DFF
add mapped point u_rf/regs[11][28]/q u_rf/regs_reg[11][28]/Q -type DFF DFF
add mapped point u_rf/regs[11][29]/q u_rf/regs_reg[11][29]/Q -type DFF DFF
add mapped point u_rf/regs[11][30]/q u_rf/regs_reg[11][30]/Q -type DFF DFF
add mapped point u_rf/regs[11][31]/q u_rf/regs_reg[11][31]/Q -type DFF DFF
add mapped point u_rf/regs[12][0]/q u_rf/regs_reg[12][0]/Q -type DFF DFF
add mapped point u_rf/regs[12][1]/q u_rf/regs_reg[12][1]/Q -type DFF DFF
add mapped point u_rf/regs[12][2]/q u_rf/regs_reg[12][2]/Q -type DFF DFF
add mapped point u_rf/regs[12][3]/q u_rf/regs_reg[12][3]/Q -type DFF DFF
add mapped point u_rf/regs[12][4]/q u_rf/regs_reg[12][4]/Q -type DFF DFF
add mapped point u_rf/regs[12][5]/q u_rf/regs_reg[12][5]/Q -type DFF DFF
add mapped point u_rf/regs[12][6]/q u_rf/regs_reg[12][6]/Q -type DFF DFF
add mapped point u_rf/regs[12][7]/q u_rf/regs_reg[12][7]/Q -type DFF DFF
add mapped point u_rf/regs[12][8]/q u_rf/regs_reg[12][8]/Q -type DFF DFF
add mapped point u_rf/regs[12][9]/q u_rf/regs_reg[12][9]/Q -type DFF DFF
add mapped point u_rf/regs[12][10]/q u_rf/regs_reg[12][10]/Q -type DFF DFF
add mapped point u_rf/regs[12][11]/q u_rf/regs_reg[12][11]/Q -type DFF DFF
add mapped point u_rf/regs[12][12]/q u_rf/regs_reg[12][12]/Q -type DFF DFF
add mapped point u_rf/regs[12][13]/q u_rf/regs_reg[12][13]/Q -type DFF DFF
add mapped point u_rf/regs[12][14]/q u_rf/regs_reg[12][14]/Q -type DFF DFF
add mapped point u_rf/regs[12][15]/q u_rf/regs_reg[12][15]/Q -type DFF DFF
add mapped point u_rf/regs[12][16]/q u_rf/regs_reg[12][16]/Q -type DFF DFF
add mapped point u_rf/regs[12][17]/q u_rf/regs_reg[12][17]/Q -type DFF DFF
add mapped point u_rf/regs[12][18]/q u_rf/regs_reg[12][18]/Q -type DFF DFF
add mapped point u_rf/regs[12][19]/q u_rf/regs_reg[12][19]/Q -type DFF DFF
add mapped point u_rf/regs[12][20]/q u_rf/regs_reg[12][20]/Q -type DFF DFF
add mapped point u_rf/regs[12][21]/q u_rf/regs_reg[12][21]/Q -type DFF DFF
add mapped point u_rf/regs[12][22]/q u_rf/regs_reg[12][22]/Q -type DFF DFF
add mapped point u_rf/regs[12][23]/q u_rf/regs_reg[12][23]/Q -type DFF DFF
add mapped point u_rf/regs[12][24]/q u_rf/regs_reg[12][24]/Q -type DFF DFF
add mapped point u_rf/regs[12][25]/q u_rf/regs_reg[12][25]/Q -type DFF DFF
add mapped point u_rf/regs[12][26]/q u_rf/regs_reg[12][26]/Q -type DFF DFF
add mapped point u_rf/regs[12][27]/q u_rf/regs_reg[12][27]/Q -type DFF DFF
add mapped point u_rf/regs[12][28]/q u_rf/regs_reg[12][28]/Q -type DFF DFF
add mapped point u_rf/regs[12][29]/q u_rf/regs_reg[12][29]/Q -type DFF DFF
add mapped point u_rf/regs[12][30]/q u_rf/regs_reg[12][30]/Q -type DFF DFF
add mapped point u_rf/regs[12][31]/q u_rf/regs_reg[12][31]/Q -type DFF DFF
add mapped point u_rf/regs[13][0]/q u_rf/regs_reg[13][0]/Q -type DFF DFF
add mapped point u_rf/regs[13][1]/q u_rf/regs_reg[13][1]/Q -type DFF DFF
add mapped point u_rf/regs[13][2]/q u_rf/regs_reg[13][2]/Q -type DFF DFF
add mapped point u_rf/regs[13][3]/q u_rf/regs_reg[13][3]/Q -type DFF DFF
add mapped point u_rf/regs[13][4]/q u_rf/regs_reg[13][4]/Q -type DFF DFF
add mapped point u_rf/regs[13][5]/q u_rf/regs_reg[13][5]/Q -type DFF DFF
add mapped point u_rf/regs[13][6]/q u_rf/regs_reg[13][6]/Q -type DFF DFF
add mapped point u_rf/regs[13][7]/q u_rf/regs_reg[13][7]/Q -type DFF DFF
add mapped point u_rf/regs[13][8]/q u_rf/regs_reg[13][8]/Q -type DFF DFF
add mapped point u_rf/regs[13][9]/q u_rf/regs_reg[13][9]/Q -type DFF DFF
add mapped point u_rf/regs[13][10]/q u_rf/regs_reg[13][10]/Q -type DFF DFF
add mapped point u_rf/regs[13][11]/q u_rf/regs_reg[13][11]/Q -type DFF DFF
add mapped point u_rf/regs[13][12]/q u_rf/regs_reg[13][12]/Q -type DFF DFF
add mapped point u_rf/regs[13][13]/q u_rf/regs_reg[13][13]/Q -type DFF DFF
add mapped point u_rf/regs[13][14]/q u_rf/regs_reg[13][14]/Q -type DFF DFF
add mapped point u_rf/regs[13][15]/q u_rf/regs_reg[13][15]/Q -type DFF DFF
add mapped point u_rf/regs[13][16]/q u_rf/regs_reg[13][16]/Q -type DFF DFF
add mapped point u_rf/regs[13][17]/q u_rf/regs_reg[13][17]/Q -type DFF DFF
add mapped point u_rf/regs[13][18]/q u_rf/regs_reg[13][18]/Q -type DFF DFF
add mapped point u_rf/regs[13][19]/q u_rf/regs_reg[13][19]/Q -type DFF DFF
add mapped point u_rf/regs[13][20]/q u_rf/regs_reg[13][20]/Q -type DFF DFF
add mapped point u_rf/regs[13][21]/q u_rf/regs_reg[13][21]/Q -type DFF DFF
add mapped point u_rf/regs[13][22]/q u_rf/regs_reg[13][22]/Q -type DFF DFF
add mapped point u_rf/regs[13][23]/q u_rf/regs_reg[13][23]/Q -type DFF DFF
add mapped point u_rf/regs[13][24]/q u_rf/regs_reg[13][24]/Q -type DFF DFF
add mapped point u_rf/regs[13][25]/q u_rf/regs_reg[13][25]/Q -type DFF DFF
add mapped point u_rf/regs[13][26]/q u_rf/regs_reg[13][26]/Q -type DFF DFF
add mapped point u_rf/regs[13][27]/q u_rf/regs_reg[13][27]/Q -type DFF DFF
add mapped point u_rf/regs[13][28]/q u_rf/regs_reg[13][28]/Q -type DFF DFF
add mapped point u_rf/regs[13][29]/q u_rf/regs_reg[13][29]/Q -type DFF DFF
add mapped point u_rf/regs[13][30]/q u_rf/regs_reg[13][30]/Q -type DFF DFF
add mapped point u_rf/regs[13][31]/q u_rf/regs_reg[13][31]/Q -type DFF DFF
add mapped point u_rf/regs[14][0]/q u_rf/regs_reg[14][0]/Q -type DFF DFF
add mapped point u_rf/regs[14][1]/q u_rf/regs_reg[14][1]/Q -type DFF DFF
add mapped point u_rf/regs[14][2]/q u_rf/regs_reg[14][2]/Q -type DFF DFF
add mapped point u_rf/regs[14][3]/q u_rf/regs_reg[14][3]/Q -type DFF DFF
add mapped point u_rf/regs[14][4]/q u_rf/regs_reg[14][4]/Q -type DFF DFF
add mapped point u_rf/regs[14][5]/q u_rf/regs_reg[14][5]/Q -type DFF DFF
add mapped point u_rf/regs[14][6]/q u_rf/regs_reg[14][6]/Q -type DFF DFF
add mapped point u_rf/regs[14][7]/q u_rf/regs_reg[14][7]/Q -type DFF DFF
add mapped point u_rf/regs[14][8]/q u_rf/regs_reg[14][8]/Q -type DFF DFF
add mapped point u_rf/regs[14][9]/q u_rf/regs_reg[14][9]/Q -type DFF DFF
add mapped point u_rf/regs[14][10]/q u_rf/regs_reg[14][10]/Q -type DFF DFF
add mapped point u_rf/regs[14][11]/q u_rf/regs_reg[14][11]/Q -type DFF DFF
add mapped point u_rf/regs[14][12]/q u_rf/regs_reg[14][12]/Q -type DFF DFF
add mapped point u_rf/regs[14][13]/q u_rf/regs_reg[14][13]/Q -type DFF DFF
add mapped point u_rf/regs[14][14]/q u_rf/regs_reg[14][14]/Q -type DFF DFF
add mapped point u_rf/regs[14][15]/q u_rf/regs_reg[14][15]/Q -type DFF DFF
add mapped point u_rf/regs[14][16]/q u_rf/regs_reg[14][16]/Q -type DFF DFF
add mapped point u_rf/regs[14][17]/q u_rf/regs_reg[14][17]/Q -type DFF DFF
add mapped point u_rf/regs[14][18]/q u_rf/regs_reg[14][18]/Q -type DFF DFF
add mapped point u_rf/regs[14][19]/q u_rf/regs_reg[14][19]/Q -type DFF DFF
add mapped point u_rf/regs[14][20]/q u_rf/regs_reg[14][20]/Q -type DFF DFF
add mapped point u_rf/regs[14][21]/q u_rf/regs_reg[14][21]/Q -type DFF DFF
add mapped point u_rf/regs[14][22]/q u_rf/regs_reg[14][22]/Q -type DFF DFF
add mapped point u_rf/regs[14][23]/q u_rf/regs_reg[14][23]/Q -type DFF DFF
add mapped point u_rf/regs[14][24]/q u_rf/regs_reg[14][24]/Q -type DFF DFF
add mapped point u_rf/regs[14][25]/q u_rf/regs_reg[14][25]/Q -type DFF DFF
add mapped point u_rf/regs[14][26]/q u_rf/regs_reg[14][26]/Q -type DFF DFF
add mapped point u_rf/regs[14][27]/q u_rf/regs_reg[14][27]/Q -type DFF DFF
add mapped point u_rf/regs[14][28]/q u_rf/regs_reg[14][28]/Q -type DFF DFF
add mapped point u_rf/regs[14][29]/q u_rf/regs_reg[14][29]/Q -type DFF DFF
add mapped point u_rf/regs[14][30]/q u_rf/regs_reg[14][30]/Q -type DFF DFF
add mapped point u_rf/regs[14][31]/q u_rf/regs_reg[14][31]/Q -type DFF DFF
add mapped point u_rf/regs[15][0]/q u_rf/regs_reg[15][0]/Q -type DFF DFF
add mapped point u_rf/regs[15][1]/q u_rf/regs_reg[15][1]/Q -type DFF DFF
add mapped point u_rf/regs[15][2]/q u_rf/regs_reg[15][2]/Q -type DFF DFF
add mapped point u_rf/regs[15][3]/q u_rf/regs_reg[15][3]/Q -type DFF DFF
add mapped point u_rf/regs[15][4]/q u_rf/regs_reg[15][4]/Q -type DFF DFF
add mapped point u_rf/regs[15][5]/q u_rf/regs_reg[15][5]/Q -type DFF DFF
add mapped point u_rf/regs[15][6]/q u_rf/regs_reg[15][6]/Q -type DFF DFF
add mapped point u_rf/regs[15][7]/q u_rf/regs_reg[15][7]/Q -type DFF DFF
add mapped point u_rf/regs[15][8]/q u_rf/regs_reg[15][8]/Q -type DFF DFF
add mapped point u_rf/regs[15][9]/q u_rf/regs_reg[15][9]/Q -type DFF DFF
add mapped point u_rf/regs[15][10]/q u_rf/regs_reg[15][10]/Q -type DFF DFF
add mapped point u_rf/regs[15][11]/q u_rf/regs_reg[15][11]/Q -type DFF DFF
add mapped point u_rf/regs[15][12]/q u_rf/regs_reg[15][12]/Q -type DFF DFF
add mapped point u_rf/regs[15][13]/q u_rf/regs_reg[15][13]/Q -type DFF DFF
add mapped point u_rf/regs[15][14]/q u_rf/regs_reg[15][14]/Q -type DFF DFF
add mapped point u_rf/regs[15][15]/q u_rf/regs_reg[15][15]/Q -type DFF DFF
add mapped point u_rf/regs[15][16]/q u_rf/regs_reg[15][16]/Q -type DFF DFF
add mapped point u_rf/regs[15][17]/q u_rf/regs_reg[15][17]/Q -type DFF DFF
add mapped point u_rf/regs[15][18]/q u_rf/regs_reg[15][18]/Q -type DFF DFF
add mapped point u_rf/regs[15][19]/q u_rf/regs_reg[15][19]/Q -type DFF DFF
add mapped point u_rf/regs[15][20]/q u_rf/regs_reg[15][20]/Q -type DFF DFF
add mapped point u_rf/regs[15][21]/q u_rf/regs_reg[15][21]/Q -type DFF DFF
add mapped point u_rf/regs[15][22]/q u_rf/regs_reg[15][22]/Q -type DFF DFF
add mapped point u_rf/regs[15][23]/q u_rf/regs_reg[15][23]/Q -type DFF DFF
add mapped point u_rf/regs[15][24]/q u_rf/regs_reg[15][24]/Q -type DFF DFF
add mapped point u_rf/regs[15][25]/q u_rf/regs_reg[15][25]/Q -type DFF DFF
add mapped point u_rf/regs[15][26]/q u_rf/regs_reg[15][26]/Q -type DFF DFF
add mapped point u_rf/regs[15][27]/q u_rf/regs_reg[15][27]/Q -type DFF DFF
add mapped point u_rf/regs[15][28]/q u_rf/regs_reg[15][28]/Q -type DFF DFF
add mapped point u_rf/regs[15][29]/q u_rf/regs_reg[15][29]/Q -type DFF DFF
add mapped point u_rf/regs[15][30]/q u_rf/regs_reg[15][30]/Q -type DFF DFF
add mapped point u_rf/regs[15][31]/q u_rf/regs_reg[15][31]/Q -type DFF DFF
add mapped point u_rf/regs[16][0]/q u_rf/regs_reg[16][0]/Q -type DFF DFF
add mapped point u_rf/regs[16][1]/q u_rf/regs_reg[16][1]/Q -type DFF DFF
add mapped point u_rf/regs[16][2]/q u_rf/regs_reg[16][2]/Q -type DFF DFF
add mapped point u_rf/regs[16][3]/q u_rf/regs_reg[16][3]/Q -type DFF DFF
add mapped point u_rf/regs[16][4]/q u_rf/regs_reg[16][4]/Q -type DFF DFF
add mapped point u_rf/regs[16][5]/q u_rf/regs_reg[16][5]/Q -type DFF DFF
add mapped point u_rf/regs[16][6]/q u_rf/regs_reg[16][6]/Q -type DFF DFF
add mapped point u_rf/regs[16][7]/q u_rf/regs_reg[16][7]/Q -type DFF DFF
add mapped point u_rf/regs[16][8]/q u_rf/regs_reg[16][8]/Q -type DFF DFF
add mapped point u_rf/regs[16][9]/q u_rf/regs_reg[16][9]/Q -type DFF DFF
add mapped point u_rf/regs[16][10]/q u_rf/regs_reg[16][10]/Q -type DFF DFF
add mapped point u_rf/regs[16][11]/q u_rf/regs_reg[16][11]/Q -type DFF DFF
add mapped point u_rf/regs[16][12]/q u_rf/regs_reg[16][12]/Q -type DFF DFF
add mapped point u_rf/regs[16][13]/q u_rf/regs_reg[16][13]/Q -type DFF DFF
add mapped point u_rf/regs[16][14]/q u_rf/regs_reg[16][14]/Q -type DFF DFF
add mapped point u_rf/regs[16][15]/q u_rf/regs_reg[16][15]/Q -type DFF DFF
add mapped point u_rf/regs[16][16]/q u_rf/regs_reg[16][16]/Q -type DFF DFF
add mapped point u_rf/regs[16][17]/q u_rf/regs_reg[16][17]/Q -type DFF DFF
add mapped point u_rf/regs[16][18]/q u_rf/regs_reg[16][18]/Q -type DFF DFF
add mapped point u_rf/regs[16][19]/q u_rf/regs_reg[16][19]/Q -type DFF DFF
add mapped point u_rf/regs[16][20]/q u_rf/regs_reg[16][20]/Q -type DFF DFF
add mapped point u_rf/regs[16][21]/q u_rf/regs_reg[16][21]/Q -type DFF DFF
add mapped point u_rf/regs[16][22]/q u_rf/regs_reg[16][22]/Q -type DFF DFF
add mapped point u_rf/regs[16][23]/q u_rf/regs_reg[16][23]/Q -type DFF DFF
add mapped point u_rf/regs[16][24]/q u_rf/regs_reg[16][24]/Q -type DFF DFF
add mapped point u_rf/regs[16][25]/q u_rf/regs_reg[16][25]/Q -type DFF DFF
add mapped point u_rf/regs[16][26]/q u_rf/regs_reg[16][26]/Q -type DFF DFF
add mapped point u_rf/regs[16][27]/q u_rf/regs_reg[16][27]/Q -type DFF DFF
add mapped point u_rf/regs[16][28]/q u_rf/regs_reg[16][28]/Q -type DFF DFF
add mapped point u_rf/regs[16][29]/q u_rf/regs_reg[16][29]/Q -type DFF DFF
add mapped point u_rf/regs[16][30]/q u_rf/regs_reg[16][30]/Q -type DFF DFF
add mapped point u_rf/regs[16][31]/q u_rf/regs_reg[16][31]/Q -type DFF DFF
add mapped point u_rf/regs[17][0]/q u_rf/regs_reg[17][0]/Q -type DFF DFF
add mapped point u_rf/regs[17][1]/q u_rf/regs_reg[17][1]/Q -type DFF DFF
add mapped point u_rf/regs[17][2]/q u_rf/regs_reg[17][2]/Q -type DFF DFF
add mapped point u_rf/regs[17][3]/q u_rf/regs_reg[17][3]/Q -type DFF DFF
add mapped point u_rf/regs[17][4]/q u_rf/regs_reg[17][4]/Q -type DFF DFF
add mapped point u_rf/regs[17][5]/q u_rf/regs_reg[17][5]/Q -type DFF DFF
add mapped point u_rf/regs[17][6]/q u_rf/regs_reg[17][6]/Q -type DFF DFF
add mapped point u_rf/regs[17][7]/q u_rf/regs_reg[17][7]/Q -type DFF DFF
add mapped point u_rf/regs[17][8]/q u_rf/regs_reg[17][8]/Q -type DFF DFF
add mapped point u_rf/regs[17][9]/q u_rf/regs_reg[17][9]/Q -type DFF DFF
add mapped point u_rf/regs[17][10]/q u_rf/regs_reg[17][10]/Q -type DFF DFF
add mapped point u_rf/regs[17][11]/q u_rf/regs_reg[17][11]/Q -type DFF DFF
add mapped point u_rf/regs[17][12]/q u_rf/regs_reg[17][12]/Q -type DFF DFF
add mapped point u_rf/regs[17][13]/q u_rf/regs_reg[17][13]/Q -type DFF DFF
add mapped point u_rf/regs[17][14]/q u_rf/regs_reg[17][14]/Q -type DFF DFF
add mapped point u_rf/regs[17][15]/q u_rf/regs_reg[17][15]/Q -type DFF DFF
add mapped point u_rf/regs[17][16]/q u_rf/regs_reg[17][16]/Q -type DFF DFF
add mapped point u_rf/regs[17][17]/q u_rf/regs_reg[17][17]/Q -type DFF DFF
add mapped point u_rf/regs[17][18]/q u_rf/regs_reg[17][18]/Q -type DFF DFF
add mapped point u_rf/regs[17][19]/q u_rf/regs_reg[17][19]/Q -type DFF DFF
add mapped point u_rf/regs[17][20]/q u_rf/regs_reg[17][20]/Q -type DFF DFF
add mapped point u_rf/regs[17][21]/q u_rf/regs_reg[17][21]/Q -type DFF DFF
add mapped point u_rf/regs[17][22]/q u_rf/regs_reg[17][22]/Q -type DFF DFF
add mapped point u_rf/regs[17][23]/q u_rf/regs_reg[17][23]/Q -type DFF DFF
add mapped point u_rf/regs[17][24]/q u_rf/regs_reg[17][24]/Q -type DFF DFF
add mapped point u_rf/regs[17][25]/q u_rf/regs_reg[17][25]/Q -type DFF DFF
add mapped point u_rf/regs[17][26]/q u_rf/regs_reg[17][26]/Q -type DFF DFF
add mapped point u_rf/regs[17][27]/q u_rf/regs_reg[17][27]/Q -type DFF DFF
add mapped point u_rf/regs[17][28]/q u_rf/regs_reg[17][28]/Q -type DFF DFF
add mapped point u_rf/regs[17][29]/q u_rf/regs_reg[17][29]/Q -type DFF DFF
add mapped point u_rf/regs[17][30]/q u_rf/regs_reg[17][30]/Q -type DFF DFF
add mapped point u_rf/regs[17][31]/q u_rf/regs_reg[17][31]/Q -type DFF DFF
add mapped point u_rf/regs[18][0]/q u_rf/regs_reg[18][0]/Q -type DFF DFF
add mapped point u_rf/regs[18][1]/q u_rf/regs_reg[18][1]/Q -type DFF DFF
add mapped point u_rf/regs[18][2]/q u_rf/regs_reg[18][2]/Q -type DFF DFF
add mapped point u_rf/regs[18][3]/q u_rf/regs_reg[18][3]/Q -type DFF DFF
add mapped point u_rf/regs[18][4]/q u_rf/regs_reg[18][4]/Q -type DFF DFF
add mapped point u_rf/regs[18][5]/q u_rf/regs_reg[18][5]/Q -type DFF DFF
add mapped point u_rf/regs[18][6]/q u_rf/regs_reg[18][6]/Q -type DFF DFF
add mapped point u_rf/regs[18][7]/q u_rf/regs_reg[18][7]/Q -type DFF DFF
add mapped point u_rf/regs[18][8]/q u_rf/regs_reg[18][8]/Q -type DFF DFF
add mapped point u_rf/regs[18][9]/q u_rf/regs_reg[18][9]/Q -type DFF DFF
add mapped point u_rf/regs[18][10]/q u_rf/regs_reg[18][10]/Q -type DFF DFF
add mapped point u_rf/regs[18][11]/q u_rf/regs_reg[18][11]/Q -type DFF DFF
add mapped point u_rf/regs[18][12]/q u_rf/regs_reg[18][12]/Q -type DFF DFF
add mapped point u_rf/regs[18][13]/q u_rf/regs_reg[18][13]/Q -type DFF DFF
add mapped point u_rf/regs[18][14]/q u_rf/regs_reg[18][14]/Q -type DFF DFF
add mapped point u_rf/regs[18][15]/q u_rf/regs_reg[18][15]/Q -type DFF DFF
add mapped point u_rf/regs[18][16]/q u_rf/regs_reg[18][16]/Q -type DFF DFF
add mapped point u_rf/regs[18][17]/q u_rf/regs_reg[18][17]/Q -type DFF DFF
add mapped point u_rf/regs[18][18]/q u_rf/regs_reg[18][18]/Q -type DFF DFF
add mapped point u_rf/regs[18][19]/q u_rf/regs_reg[18][19]/Q -type DFF DFF
add mapped point u_rf/regs[18][20]/q u_rf/regs_reg[18][20]/Q -type DFF DFF
add mapped point u_rf/regs[18][21]/q u_rf/regs_reg[18][21]/Q -type DFF DFF
add mapped point u_rf/regs[18][22]/q u_rf/regs_reg[18][22]/Q -type DFF DFF
add mapped point u_rf/regs[18][23]/q u_rf/regs_reg[18][23]/Q -type DFF DFF
add mapped point u_rf/regs[18][24]/q u_rf/regs_reg[18][24]/Q -type DFF DFF
add mapped point u_rf/regs[18][25]/q u_rf/regs_reg[18][25]/Q -type DFF DFF
add mapped point u_rf/regs[18][26]/q u_rf/regs_reg[18][26]/Q -type DFF DFF
add mapped point u_rf/regs[18][27]/q u_rf/regs_reg[18][27]/Q -type DFF DFF
add mapped point u_rf/regs[18][28]/q u_rf/regs_reg[18][28]/Q -type DFF DFF
add mapped point u_rf/regs[18][29]/q u_rf/regs_reg[18][29]/Q -type DFF DFF
add mapped point u_rf/regs[18][30]/q u_rf/regs_reg[18][30]/Q -type DFF DFF
add mapped point u_rf/regs[18][31]/q u_rf/regs_reg[18][31]/Q -type DFF DFF
add mapped point u_rf/regs[19][0]/q u_rf/regs_reg[19][0]/Q -type DFF DFF
add mapped point u_rf/regs[19][1]/q u_rf/regs_reg[19][1]/Q -type DFF DFF
add mapped point u_rf/regs[19][2]/q u_rf/regs_reg[19][2]/Q -type DFF DFF
add mapped point u_rf/regs[19][3]/q u_rf/regs_reg[19][3]/Q -type DFF DFF
add mapped point u_rf/regs[19][4]/q u_rf/regs_reg[19][4]/Q -type DFF DFF
add mapped point u_rf/regs[19][5]/q u_rf/regs_reg[19][5]/Q -type DFF DFF
add mapped point u_rf/regs[19][6]/q u_rf/regs_reg[19][6]/Q -type DFF DFF
add mapped point u_rf/regs[19][7]/q u_rf/regs_reg[19][7]/Q -type DFF DFF
add mapped point u_rf/regs[19][8]/q u_rf/regs_reg[19][8]/Q -type DFF DFF
add mapped point u_rf/regs[19][9]/q u_rf/regs_reg[19][9]/Q -type DFF DFF
add mapped point u_rf/regs[19][10]/q u_rf/regs_reg[19][10]/Q -type DFF DFF
add mapped point u_rf/regs[19][11]/q u_rf/regs_reg[19][11]/Q -type DFF DFF
add mapped point u_rf/regs[19][12]/q u_rf/regs_reg[19][12]/Q -type DFF DFF
add mapped point u_rf/regs[19][13]/q u_rf/regs_reg[19][13]/Q -type DFF DFF
add mapped point u_rf/regs[19][14]/q u_rf/regs_reg[19][14]/Q -type DFF DFF
add mapped point u_rf/regs[19][15]/q u_rf/regs_reg[19][15]/Q -type DFF DFF
add mapped point u_rf/regs[19][16]/q u_rf/regs_reg[19][16]/Q -type DFF DFF
add mapped point u_rf/regs[19][17]/q u_rf/regs_reg[19][17]/Q -type DFF DFF
add mapped point u_rf/regs[19][18]/q u_rf/regs_reg[19][18]/Q -type DFF DFF
add mapped point u_rf/regs[19][19]/q u_rf/regs_reg[19][19]/Q -type DFF DFF
add mapped point u_rf/regs[19][20]/q u_rf/regs_reg[19][20]/Q -type DFF DFF
add mapped point u_rf/regs[19][21]/q u_rf/regs_reg[19][21]/Q -type DFF DFF
add mapped point u_rf/regs[19][22]/q u_rf/regs_reg[19][22]/Q -type DFF DFF
add mapped point u_rf/regs[19][23]/q u_rf/regs_reg[19][23]/Q -type DFF DFF
add mapped point u_rf/regs[19][24]/q u_rf/regs_reg[19][24]/Q -type DFF DFF
add mapped point u_rf/regs[19][25]/q u_rf/regs_reg[19][25]/Q -type DFF DFF
add mapped point u_rf/regs[19][26]/q u_rf/regs_reg[19][26]/Q -type DFF DFF
add mapped point u_rf/regs[19][27]/q u_rf/regs_reg[19][27]/Q -type DFF DFF
add mapped point u_rf/regs[19][28]/q u_rf/regs_reg[19][28]/Q -type DFF DFF
add mapped point u_rf/regs[19][29]/q u_rf/regs_reg[19][29]/Q -type DFF DFF
add mapped point u_rf/regs[19][30]/q u_rf/regs_reg[19][30]/Q -type DFF DFF
add mapped point u_rf/regs[19][31]/q u_rf/regs_reg[19][31]/Q -type DFF DFF
add mapped point u_rf/regs[20][0]/q u_rf/regs_reg[20][0]/Q -type DFF DFF
add mapped point u_rf/regs[20][1]/q u_rf/regs_reg[20][1]/Q -type DFF DFF
add mapped point u_rf/regs[20][2]/q u_rf/regs_reg[20][2]/Q -type DFF DFF
add mapped point u_rf/regs[20][3]/q u_rf/regs_reg[20][3]/Q -type DFF DFF
add mapped point u_rf/regs[20][4]/q u_rf/regs_reg[20][4]/Q -type DFF DFF
add mapped point u_rf/regs[20][5]/q u_rf/regs_reg[20][5]/Q -type DFF DFF
add mapped point u_rf/regs[20][6]/q u_rf/regs_reg[20][6]/Q -type DFF DFF
add mapped point u_rf/regs[20][7]/q u_rf/regs_reg[20][7]/Q -type DFF DFF
add mapped point u_rf/regs[20][8]/q u_rf/regs_reg[20][8]/Q -type DFF DFF
add mapped point u_rf/regs[20][9]/q u_rf/regs_reg[20][9]/Q -type DFF DFF
add mapped point u_rf/regs[20][10]/q u_rf/regs_reg[20][10]/Q -type DFF DFF
add mapped point u_rf/regs[20][11]/q u_rf/regs_reg[20][11]/Q -type DFF DFF
add mapped point u_rf/regs[20][12]/q u_rf/regs_reg[20][12]/Q -type DFF DFF
add mapped point u_rf/regs[20][13]/q u_rf/regs_reg[20][13]/Q -type DFF DFF
add mapped point u_rf/regs[20][14]/q u_rf/regs_reg[20][14]/Q -type DFF DFF
add mapped point u_rf/regs[20][15]/q u_rf/regs_reg[20][15]/Q -type DFF DFF
add mapped point u_rf/regs[20][16]/q u_rf/regs_reg[20][16]/Q -type DFF DFF
add mapped point u_rf/regs[20][17]/q u_rf/regs_reg[20][17]/Q -type DFF DFF
add mapped point u_rf/regs[20][18]/q u_rf/regs_reg[20][18]/Q -type DFF DFF
add mapped point u_rf/regs[20][19]/q u_rf/regs_reg[20][19]/Q -type DFF DFF
add mapped point u_rf/regs[20][20]/q u_rf/regs_reg[20][20]/Q -type DFF DFF
add mapped point u_rf/regs[20][21]/q u_rf/regs_reg[20][21]/Q -type DFF DFF
add mapped point u_rf/regs[20][22]/q u_rf/regs_reg[20][22]/Q -type DFF DFF
add mapped point u_rf/regs[20][23]/q u_rf/regs_reg[20][23]/Q -type DFF DFF
add mapped point u_rf/regs[20][24]/q u_rf/regs_reg[20][24]/Q -type DFF DFF
add mapped point u_rf/regs[20][25]/q u_rf/regs_reg[20][25]/Q -type DFF DFF
add mapped point u_rf/regs[20][26]/q u_rf/regs_reg[20][26]/Q -type DFF DFF
add mapped point u_rf/regs[20][27]/q u_rf/regs_reg[20][27]/Q -type DFF DFF
add mapped point u_rf/regs[20][28]/q u_rf/regs_reg[20][28]/Q -type DFF DFF
add mapped point u_rf/regs[20][29]/q u_rf/regs_reg[20][29]/Q -type DFF DFF
add mapped point u_rf/regs[20][30]/q u_rf/regs_reg[20][30]/Q -type DFF DFF
add mapped point u_rf/regs[20][31]/q u_rf/regs_reg[20][31]/Q -type DFF DFF
add mapped point u_rf/regs[21][0]/q u_rf/regs_reg[21][0]/Q -type DFF DFF
add mapped point u_rf/regs[21][1]/q u_rf/regs_reg[21][1]/Q -type DFF DFF
add mapped point u_rf/regs[21][2]/q u_rf/regs_reg[21][2]/Q -type DFF DFF
add mapped point u_rf/regs[21][3]/q u_rf/regs_reg[21][3]/Q -type DFF DFF
add mapped point u_rf/regs[21][4]/q u_rf/regs_reg[21][4]/Q -type DFF DFF
add mapped point u_rf/regs[21][5]/q u_rf/regs_reg[21][5]/Q -type DFF DFF
add mapped point u_rf/regs[21][6]/q u_rf/regs_reg[21][6]/Q -type DFF DFF
add mapped point u_rf/regs[21][7]/q u_rf/regs_reg[21][7]/Q -type DFF DFF
add mapped point u_rf/regs[21][8]/q u_rf/regs_reg[21][8]/Q -type DFF DFF
add mapped point u_rf/regs[21][9]/q u_rf/regs_reg[21][9]/Q -type DFF DFF
add mapped point u_rf/regs[21][10]/q u_rf/regs_reg[21][10]/Q -type DFF DFF
add mapped point u_rf/regs[21][11]/q u_rf/regs_reg[21][11]/Q -type DFF DFF
add mapped point u_rf/regs[21][12]/q u_rf/regs_reg[21][12]/Q -type DFF DFF
add mapped point u_rf/regs[21][13]/q u_rf/regs_reg[21][13]/Q -type DFF DFF
add mapped point u_rf/regs[21][14]/q u_rf/regs_reg[21][14]/Q -type DFF DFF
add mapped point u_rf/regs[21][15]/q u_rf/regs_reg[21][15]/Q -type DFF DFF
add mapped point u_rf/regs[21][16]/q u_rf/regs_reg[21][16]/Q -type DFF DFF
add mapped point u_rf/regs[21][17]/q u_rf/regs_reg[21][17]/Q -type DFF DFF
add mapped point u_rf/regs[21][18]/q u_rf/regs_reg[21][18]/Q -type DFF DFF
add mapped point u_rf/regs[21][19]/q u_rf/regs_reg[21][19]/Q -type DFF DFF
add mapped point u_rf/regs[21][20]/q u_rf/regs_reg[21][20]/Q -type DFF DFF
add mapped point u_rf/regs[21][21]/q u_rf/regs_reg[21][21]/Q -type DFF DFF
add mapped point u_rf/regs[21][22]/q u_rf/regs_reg[21][22]/Q -type DFF DFF
add mapped point u_rf/regs[21][23]/q u_rf/regs_reg[21][23]/Q -type DFF DFF
add mapped point u_rf/regs[21][24]/q u_rf/regs_reg[21][24]/Q -type DFF DFF
add mapped point u_rf/regs[21][25]/q u_rf/regs_reg[21][25]/Q -type DFF DFF
add mapped point u_rf/regs[21][26]/q u_rf/regs_reg[21][26]/Q -type DFF DFF
add mapped point u_rf/regs[21][27]/q u_rf/regs_reg[21][27]/Q -type DFF DFF
add mapped point u_rf/regs[21][28]/q u_rf/regs_reg[21][28]/Q -type DFF DFF
add mapped point u_rf/regs[21][29]/q u_rf/regs_reg[21][29]/Q -type DFF DFF
add mapped point u_rf/regs[21][30]/q u_rf/regs_reg[21][30]/Q -type DFF DFF
add mapped point u_rf/regs[21][31]/q u_rf/regs_reg[21][31]/Q -type DFF DFF
add mapped point u_rf/regs[22][0]/q u_rf/regs_reg[22][0]/Q -type DFF DFF
add mapped point u_rf/regs[22][1]/q u_rf/regs_reg[22][1]/Q -type DFF DFF
add mapped point u_rf/regs[22][2]/q u_rf/regs_reg[22][2]/Q -type DFF DFF
add mapped point u_rf/regs[22][3]/q u_rf/regs_reg[22][3]/Q -type DFF DFF
add mapped point u_rf/regs[22][4]/q u_rf/regs_reg[22][4]/Q -type DFF DFF
add mapped point u_rf/regs[22][5]/q u_rf/regs_reg[22][5]/Q -type DFF DFF
add mapped point u_rf/regs[22][6]/q u_rf/regs_reg[22][6]/Q -type DFF DFF
add mapped point u_rf/regs[22][7]/q u_rf/regs_reg[22][7]/Q -type DFF DFF
add mapped point u_rf/regs[22][8]/q u_rf/regs_reg[22][8]/Q -type DFF DFF
add mapped point u_rf/regs[22][9]/q u_rf/regs_reg[22][9]/Q -type DFF DFF
add mapped point u_rf/regs[22][10]/q u_rf/regs_reg[22][10]/Q -type DFF DFF
add mapped point u_rf/regs[22][11]/q u_rf/regs_reg[22][11]/Q -type DFF DFF
add mapped point u_rf/regs[22][12]/q u_rf/regs_reg[22][12]/Q -type DFF DFF
add mapped point u_rf/regs[22][13]/q u_rf/regs_reg[22][13]/Q -type DFF DFF
add mapped point u_rf/regs[22][14]/q u_rf/regs_reg[22][14]/Q -type DFF DFF
add mapped point u_rf/regs[22][15]/q u_rf/regs_reg[22][15]/Q -type DFF DFF
add mapped point u_rf/regs[22][16]/q u_rf/regs_reg[22][16]/Q -type DFF DFF
add mapped point u_rf/regs[22][17]/q u_rf/regs_reg[22][17]/Q -type DFF DFF
add mapped point u_rf/regs[22][18]/q u_rf/regs_reg[22][18]/Q -type DFF DFF
add mapped point u_rf/regs[22][19]/q u_rf/regs_reg[22][19]/Q -type DFF DFF
add mapped point u_rf/regs[22][20]/q u_rf/regs_reg[22][20]/Q -type DFF DFF
add mapped point u_rf/regs[22][21]/q u_rf/regs_reg[22][21]/Q -type DFF DFF
add mapped point u_rf/regs[22][22]/q u_rf/regs_reg[22][22]/Q -type DFF DFF
add mapped point u_rf/regs[22][23]/q u_rf/regs_reg[22][23]/Q -type DFF DFF
add mapped point u_rf/regs[22][24]/q u_rf/regs_reg[22][24]/Q -type DFF DFF
add mapped point u_rf/regs[22][25]/q u_rf/regs_reg[22][25]/Q -type DFF DFF
add mapped point u_rf/regs[22][26]/q u_rf/regs_reg[22][26]/Q -type DFF DFF
add mapped point u_rf/regs[22][27]/q u_rf/regs_reg[22][27]/Q -type DFF DFF
add mapped point u_rf/regs[22][28]/q u_rf/regs_reg[22][28]/Q -type DFF DFF
add mapped point u_rf/regs[22][29]/q u_rf/regs_reg[22][29]/Q -type DFF DFF
add mapped point u_rf/regs[22][30]/q u_rf/regs_reg[22][30]/Q -type DFF DFF
add mapped point u_rf/regs[22][31]/q u_rf/regs_reg[22][31]/Q -type DFF DFF
add mapped point u_rf/regs[23][0]/q u_rf/regs_reg[23][0]/Q -type DFF DFF
add mapped point u_rf/regs[23][1]/q u_rf/regs_reg[23][1]/Q -type DFF DFF
add mapped point u_rf/regs[23][2]/q u_rf/regs_reg[23][2]/Q -type DFF DFF
add mapped point u_rf/regs[23][3]/q u_rf/regs_reg[23][3]/Q -type DFF DFF
add mapped point u_rf/regs[23][4]/q u_rf/regs_reg[23][4]/Q -type DFF DFF
add mapped point u_rf/regs[23][5]/q u_rf/regs_reg[23][5]/Q -type DFF DFF
add mapped point u_rf/regs[23][6]/q u_rf/regs_reg[23][6]/Q -type DFF DFF
add mapped point u_rf/regs[23][7]/q u_rf/regs_reg[23][7]/Q -type DFF DFF
add mapped point u_rf/regs[23][8]/q u_rf/regs_reg[23][8]/Q -type DFF DFF
add mapped point u_rf/regs[23][9]/q u_rf/regs_reg[23][9]/Q -type DFF DFF
add mapped point u_rf/regs[23][10]/q u_rf/regs_reg[23][10]/Q -type DFF DFF
add mapped point u_rf/regs[23][11]/q u_rf/regs_reg[23][11]/Q -type DFF DFF
add mapped point u_rf/regs[23][12]/q u_rf/regs_reg[23][12]/Q -type DFF DFF
add mapped point u_rf/regs[23][13]/q u_rf/regs_reg[23][13]/Q -type DFF DFF
add mapped point u_rf/regs[23][14]/q u_rf/regs_reg[23][14]/Q -type DFF DFF
add mapped point u_rf/regs[23][15]/q u_rf/regs_reg[23][15]/Q -type DFF DFF
add mapped point u_rf/regs[23][16]/q u_rf/regs_reg[23][16]/Q -type DFF DFF
add mapped point u_rf/regs[23][17]/q u_rf/regs_reg[23][17]/Q -type DFF DFF
add mapped point u_rf/regs[23][18]/q u_rf/regs_reg[23][18]/Q -type DFF DFF
add mapped point u_rf/regs[23][19]/q u_rf/regs_reg[23][19]/Q -type DFF DFF
add mapped point u_rf/regs[23][20]/q u_rf/regs_reg[23][20]/Q -type DFF DFF
add mapped point u_rf/regs[23][21]/q u_rf/regs_reg[23][21]/Q -type DFF DFF
add mapped point u_rf/regs[23][22]/q u_rf/regs_reg[23][22]/Q -type DFF DFF
add mapped point u_rf/regs[23][23]/q u_rf/regs_reg[23][23]/Q -type DFF DFF
add mapped point u_rf/regs[23][24]/q u_rf/regs_reg[23][24]/Q -type DFF DFF
add mapped point u_rf/regs[23][25]/q u_rf/regs_reg[23][25]/Q -type DFF DFF
add mapped point u_rf/regs[23][26]/q u_rf/regs_reg[23][26]/Q -type DFF DFF
add mapped point u_rf/regs[23][27]/q u_rf/regs_reg[23][27]/Q -type DFF DFF
add mapped point u_rf/regs[23][28]/q u_rf/regs_reg[23][28]/Q -type DFF DFF
add mapped point u_rf/regs[23][29]/q u_rf/regs_reg[23][29]/Q -type DFF DFF
add mapped point u_rf/regs[23][30]/q u_rf/regs_reg[23][30]/Q -type DFF DFF
add mapped point u_rf/regs[23][31]/q u_rf/regs_reg[23][31]/Q -type DFF DFF
add mapped point u_rf/regs[24][0]/q u_rf/regs_reg[24][0]/Q -type DFF DFF
add mapped point u_rf/regs[24][1]/q u_rf/regs_reg[24][1]/Q -type DFF DFF
add mapped point u_rf/regs[24][2]/q u_rf/regs_reg[24][2]/Q -type DFF DFF
add mapped point u_rf/regs[24][3]/q u_rf/regs_reg[24][3]/Q -type DFF DFF
add mapped point u_rf/regs[24][4]/q u_rf/regs_reg[24][4]/Q -type DFF DFF
add mapped point u_rf/regs[24][5]/q u_rf/regs_reg[24][5]/Q -type DFF DFF
add mapped point u_rf/regs[24][6]/q u_rf/regs_reg[24][6]/Q -type DFF DFF
add mapped point u_rf/regs[24][7]/q u_rf/regs_reg[24][7]/Q -type DFF DFF
add mapped point u_rf/regs[24][8]/q u_rf/regs_reg[24][8]/Q -type DFF DFF
add mapped point u_rf/regs[24][9]/q u_rf/regs_reg[24][9]/Q -type DFF DFF
add mapped point u_rf/regs[24][10]/q u_rf/regs_reg[24][10]/Q -type DFF DFF
add mapped point u_rf/regs[24][11]/q u_rf/regs_reg[24][11]/Q -type DFF DFF
add mapped point u_rf/regs[24][12]/q u_rf/regs_reg[24][12]/Q -type DFF DFF
add mapped point u_rf/regs[24][13]/q u_rf/regs_reg[24][13]/Q -type DFF DFF
add mapped point u_rf/regs[24][14]/q u_rf/regs_reg[24][14]/Q -type DFF DFF
add mapped point u_rf/regs[24][15]/q u_rf/regs_reg[24][15]/Q -type DFF DFF
add mapped point u_rf/regs[24][16]/q u_rf/regs_reg[24][16]/Q -type DFF DFF
add mapped point u_rf/regs[24][17]/q u_rf/regs_reg[24][17]/Q -type DFF DFF
add mapped point u_rf/regs[24][18]/q u_rf/regs_reg[24][18]/Q -type DFF DFF
add mapped point u_rf/regs[24][19]/q u_rf/regs_reg[24][19]/Q -type DFF DFF
add mapped point u_rf/regs[24][20]/q u_rf/regs_reg[24][20]/Q -type DFF DFF
add mapped point u_rf/regs[24][21]/q u_rf/regs_reg[24][21]/Q -type DFF DFF
add mapped point u_rf/regs[24][22]/q u_rf/regs_reg[24][22]/Q -type DFF DFF
add mapped point u_rf/regs[24][23]/q u_rf/regs_reg[24][23]/Q -type DFF DFF
add mapped point u_rf/regs[24][24]/q u_rf/regs_reg[24][24]/Q -type DFF DFF
add mapped point u_rf/regs[24][25]/q u_rf/regs_reg[24][25]/Q -type DFF DFF
add mapped point u_rf/regs[24][26]/q u_rf/regs_reg[24][26]/Q -type DFF DFF
add mapped point u_rf/regs[24][27]/q u_rf/regs_reg[24][27]/Q -type DFF DFF
add mapped point u_rf/regs[24][28]/q u_rf/regs_reg[24][28]/Q -type DFF DFF
add mapped point u_rf/regs[24][29]/q u_rf/regs_reg[24][29]/Q -type DFF DFF
add mapped point u_rf/regs[24][30]/q u_rf/regs_reg[24][30]/Q -type DFF DFF
add mapped point u_rf/regs[24][31]/q u_rf/regs_reg[24][31]/Q -type DFF DFF
add mapped point u_rf/regs[25][0]/q u_rf/regs_reg[25][0]/Q -type DFF DFF
add mapped point u_rf/regs[25][1]/q u_rf/regs_reg[25][1]/Q -type DFF DFF
add mapped point u_rf/regs[25][2]/q u_rf/regs_reg[25][2]/Q -type DFF DFF
add mapped point u_rf/regs[25][3]/q u_rf/regs_reg[25][3]/Q -type DFF DFF
add mapped point u_rf/regs[25][4]/q u_rf/regs_reg[25][4]/Q -type DFF DFF
add mapped point u_rf/regs[25][5]/q u_rf/regs_reg[25][5]/Q -type DFF DFF
add mapped point u_rf/regs[25][6]/q u_rf/regs_reg[25][6]/Q -type DFF DFF
add mapped point u_rf/regs[25][7]/q u_rf/regs_reg[25][7]/Q -type DFF DFF
add mapped point u_rf/regs[25][8]/q u_rf/regs_reg[25][8]/Q -type DFF DFF
add mapped point u_rf/regs[25][9]/q u_rf/regs_reg[25][9]/Q -type DFF DFF
add mapped point u_rf/regs[25][10]/q u_rf/regs_reg[25][10]/Q -type DFF DFF
add mapped point u_rf/regs[25][11]/q u_rf/regs_reg[25][11]/Q -type DFF DFF
add mapped point u_rf/regs[25][12]/q u_rf/regs_reg[25][12]/Q -type DFF DFF
add mapped point u_rf/regs[25][13]/q u_rf/regs_reg[25][13]/Q -type DFF DFF
add mapped point u_rf/regs[25][14]/q u_rf/regs_reg[25][14]/Q -type DFF DFF
add mapped point u_rf/regs[25][15]/q u_rf/regs_reg[25][15]/Q -type DFF DFF
add mapped point u_rf/regs[25][16]/q u_rf/regs_reg[25][16]/Q -type DFF DFF
add mapped point u_rf/regs[25][17]/q u_rf/regs_reg[25][17]/Q -type DFF DFF
add mapped point u_rf/regs[25][18]/q u_rf/regs_reg[25][18]/Q -type DFF DFF
add mapped point u_rf/regs[25][19]/q u_rf/regs_reg[25][19]/Q -type DFF DFF
add mapped point u_rf/regs[25][20]/q u_rf/regs_reg[25][20]/Q -type DFF DFF
add mapped point u_rf/regs[25][21]/q u_rf/regs_reg[25][21]/Q -type DFF DFF
add mapped point u_rf/regs[25][22]/q u_rf/regs_reg[25][22]/Q -type DFF DFF
add mapped point u_rf/regs[25][23]/q u_rf/regs_reg[25][23]/Q -type DFF DFF
add mapped point u_rf/regs[25][24]/q u_rf/regs_reg[25][24]/Q -type DFF DFF
add mapped point u_rf/regs[25][25]/q u_rf/regs_reg[25][25]/Q -type DFF DFF
add mapped point u_rf/regs[25][26]/q u_rf/regs_reg[25][26]/Q -type DFF DFF
add mapped point u_rf/regs[25][27]/q u_rf/regs_reg[25][27]/Q -type DFF DFF
add mapped point u_rf/regs[25][28]/q u_rf/regs_reg[25][28]/Q -type DFF DFF
add mapped point u_rf/regs[25][29]/q u_rf/regs_reg[25][29]/Q -type DFF DFF
add mapped point u_rf/regs[25][30]/q u_rf/regs_reg[25][30]/Q -type DFF DFF
add mapped point u_rf/regs[25][31]/q u_rf/regs_reg[25][31]/Q -type DFF DFF
add mapped point u_rf/regs[26][0]/q u_rf/regs_reg[26][0]/Q -type DFF DFF
add mapped point u_rf/regs[26][1]/q u_rf/regs_reg[26][1]/Q -type DFF DFF
add mapped point u_rf/regs[26][2]/q u_rf/regs_reg[26][2]/Q -type DFF DFF
add mapped point u_rf/regs[26][3]/q u_rf/regs_reg[26][3]/Q -type DFF DFF
add mapped point u_rf/regs[26][4]/q u_rf/regs_reg[26][4]/Q -type DFF DFF
add mapped point u_rf/regs[26][5]/q u_rf/regs_reg[26][5]/Q -type DFF DFF
add mapped point u_rf/regs[26][6]/q u_rf/regs_reg[26][6]/Q -type DFF DFF
add mapped point u_rf/regs[26][7]/q u_rf/regs_reg[26][7]/Q -type DFF DFF
add mapped point u_rf/regs[26][8]/q u_rf/regs_reg[26][8]/Q -type DFF DFF
add mapped point u_rf/regs[26][9]/q u_rf/regs_reg[26][9]/Q -type DFF DFF
add mapped point u_rf/regs[26][10]/q u_rf/regs_reg[26][10]/Q -type DFF DFF
add mapped point u_rf/regs[26][11]/q u_rf/regs_reg[26][11]/Q -type DFF DFF
add mapped point u_rf/regs[26][12]/q u_rf/regs_reg[26][12]/Q -type DFF DFF
add mapped point u_rf/regs[26][13]/q u_rf/regs_reg[26][13]/Q -type DFF DFF
add mapped point u_rf/regs[26][14]/q u_rf/regs_reg[26][14]/Q -type DFF DFF
add mapped point u_rf/regs[26][15]/q u_rf/regs_reg[26][15]/Q -type DFF DFF
add mapped point u_rf/regs[26][16]/q u_rf/regs_reg[26][16]/Q -type DFF DFF
add mapped point u_rf/regs[26][17]/q u_rf/regs_reg[26][17]/Q -type DFF DFF
add mapped point u_rf/regs[26][18]/q u_rf/regs_reg[26][18]/Q -type DFF DFF
add mapped point u_rf/regs[26][19]/q u_rf/regs_reg[26][19]/Q -type DFF DFF
add mapped point u_rf/regs[26][20]/q u_rf/regs_reg[26][20]/Q -type DFF DFF
add mapped point u_rf/regs[26][21]/q u_rf/regs_reg[26][21]/Q -type DFF DFF
add mapped point u_rf/regs[26][22]/q u_rf/regs_reg[26][22]/Q -type DFF DFF
add mapped point u_rf/regs[26][23]/q u_rf/regs_reg[26][23]/Q -type DFF DFF
add mapped point u_rf/regs[26][24]/q u_rf/regs_reg[26][24]/Q -type DFF DFF
add mapped point u_rf/regs[26][25]/q u_rf/regs_reg[26][25]/Q -type DFF DFF
add mapped point u_rf/regs[26][26]/q u_rf/regs_reg[26][26]/Q -type DFF DFF
add mapped point u_rf/regs[26][27]/q u_rf/regs_reg[26][27]/Q -type DFF DFF
add mapped point u_rf/regs[26][28]/q u_rf/regs_reg[26][28]/Q -type DFF DFF
add mapped point u_rf/regs[26][29]/q u_rf/regs_reg[26][29]/Q -type DFF DFF
add mapped point u_rf/regs[26][30]/q u_rf/regs_reg[26][30]/Q -type DFF DFF
add mapped point u_rf/regs[26][31]/q u_rf/regs_reg[26][31]/Q -type DFF DFF
add mapped point u_rf/regs[27][0]/q u_rf/regs_reg[27][0]/Q -type DFF DFF
add mapped point u_rf/regs[27][1]/q u_rf/regs_reg[27][1]/Q -type DFF DFF
add mapped point u_rf/regs[27][2]/q u_rf/regs_reg[27][2]/Q -type DFF DFF
add mapped point u_rf/regs[27][3]/q u_rf/regs_reg[27][3]/Q -type DFF DFF
add mapped point u_rf/regs[27][4]/q u_rf/regs_reg[27][4]/Q -type DFF DFF
add mapped point u_rf/regs[27][5]/q u_rf/regs_reg[27][5]/Q -type DFF DFF
add mapped point u_rf/regs[27][6]/q u_rf/regs_reg[27][6]/Q -type DFF DFF
add mapped point u_rf/regs[27][7]/q u_rf/regs_reg[27][7]/Q -type DFF DFF
add mapped point u_rf/regs[27][8]/q u_rf/regs_reg[27][8]/Q -type DFF DFF
add mapped point u_rf/regs[27][9]/q u_rf/regs_reg[27][9]/Q -type DFF DFF
add mapped point u_rf/regs[27][10]/q u_rf/regs_reg[27][10]/Q -type DFF DFF
add mapped point u_rf/regs[27][11]/q u_rf/regs_reg[27][11]/Q -type DFF DFF
add mapped point u_rf/regs[27][12]/q u_rf/regs_reg[27][12]/Q -type DFF DFF
add mapped point u_rf/regs[27][13]/q u_rf/regs_reg[27][13]/Q -type DFF DFF
add mapped point u_rf/regs[27][14]/q u_rf/regs_reg[27][14]/Q -type DFF DFF
add mapped point u_rf/regs[27][15]/q u_rf/regs_reg[27][15]/Q -type DFF DFF
add mapped point u_rf/regs[27][16]/q u_rf/regs_reg[27][16]/Q -type DFF DFF
add mapped point u_rf/regs[27][17]/q u_rf/regs_reg[27][17]/Q -type DFF DFF
add mapped point u_rf/regs[27][18]/q u_rf/regs_reg[27][18]/Q -type DFF DFF
add mapped point u_rf/regs[27][19]/q u_rf/regs_reg[27][19]/Q -type DFF DFF
add mapped point u_rf/regs[27][20]/q u_rf/regs_reg[27][20]/Q -type DFF DFF
add mapped point u_rf/regs[27][21]/q u_rf/regs_reg[27][21]/Q -type DFF DFF
add mapped point u_rf/regs[27][22]/q u_rf/regs_reg[27][22]/Q -type DFF DFF
add mapped point u_rf/regs[27][23]/q u_rf/regs_reg[27][23]/Q -type DFF DFF
add mapped point u_rf/regs[27][24]/q u_rf/regs_reg[27][24]/Q -type DFF DFF
add mapped point u_rf/regs[27][25]/q u_rf/regs_reg[27][25]/Q -type DFF DFF
add mapped point u_rf/regs[27][26]/q u_rf/regs_reg[27][26]/Q -type DFF DFF
add mapped point u_rf/regs[27][27]/q u_rf/regs_reg[27][27]/Q -type DFF DFF
add mapped point u_rf/regs[27][28]/q u_rf/regs_reg[27][28]/Q -type DFF DFF
add mapped point u_rf/regs[27][29]/q u_rf/regs_reg[27][29]/Q -type DFF DFF
add mapped point u_rf/regs[27][30]/q u_rf/regs_reg[27][30]/Q -type DFF DFF
add mapped point u_rf/regs[27][31]/q u_rf/regs_reg[27][31]/Q -type DFF DFF
add mapped point u_rf/regs[28][0]/q u_rf/regs_reg[28][0]/Q -type DFF DFF
add mapped point u_rf/regs[28][1]/q u_rf/regs_reg[28][1]/Q -type DFF DFF
add mapped point u_rf/regs[28][2]/q u_rf/regs_reg[28][2]/Q -type DFF DFF
add mapped point u_rf/regs[28][3]/q u_rf/regs_reg[28][3]/Q -type DFF DFF
add mapped point u_rf/regs[28][4]/q u_rf/regs_reg[28][4]/Q -type DFF DFF
add mapped point u_rf/regs[28][5]/q u_rf/regs_reg[28][5]/Q -type DFF DFF
add mapped point u_rf/regs[28][6]/q u_rf/regs_reg[28][6]/Q -type DFF DFF
add mapped point u_rf/regs[28][7]/q u_rf/regs_reg[28][7]/Q -type DFF DFF
add mapped point u_rf/regs[28][8]/q u_rf/regs_reg[28][8]/Q -type DFF DFF
add mapped point u_rf/regs[28][9]/q u_rf/regs_reg[28][9]/Q -type DFF DFF
add mapped point u_rf/regs[28][10]/q u_rf/regs_reg[28][10]/Q -type DFF DFF
add mapped point u_rf/regs[28][11]/q u_rf/regs_reg[28][11]/Q -type DFF DFF
add mapped point u_rf/regs[28][12]/q u_rf/regs_reg[28][12]/Q -type DFF DFF
add mapped point u_rf/regs[28][13]/q u_rf/regs_reg[28][13]/Q -type DFF DFF
add mapped point u_rf/regs[28][14]/q u_rf/regs_reg[28][14]/Q -type DFF DFF
add mapped point u_rf/regs[28][15]/q u_rf/regs_reg[28][15]/Q -type DFF DFF
add mapped point u_rf/regs[28][16]/q u_rf/regs_reg[28][16]/Q -type DFF DFF
add mapped point u_rf/regs[28][17]/q u_rf/regs_reg[28][17]/Q -type DFF DFF
add mapped point u_rf/regs[28][18]/q u_rf/regs_reg[28][18]/Q -type DFF DFF
add mapped point u_rf/regs[28][19]/q u_rf/regs_reg[28][19]/Q -type DFF DFF
add mapped point u_rf/regs[28][20]/q u_rf/regs_reg[28][20]/Q -type DFF DFF
add mapped point u_rf/regs[28][21]/q u_rf/regs_reg[28][21]/Q -type DFF DFF
add mapped point u_rf/regs[28][22]/q u_rf/regs_reg[28][22]/Q -type DFF DFF
add mapped point u_rf/regs[28][23]/q u_rf/regs_reg[28][23]/Q -type DFF DFF
add mapped point u_rf/regs[28][24]/q u_rf/regs_reg[28][24]/Q -type DFF DFF
add mapped point u_rf/regs[28][25]/q u_rf/regs_reg[28][25]/Q -type DFF DFF
add mapped point u_rf/regs[28][26]/q u_rf/regs_reg[28][26]/Q -type DFF DFF
add mapped point u_rf/regs[28][27]/q u_rf/regs_reg[28][27]/Q -type DFF DFF
add mapped point u_rf/regs[28][28]/q u_rf/regs_reg[28][28]/Q -type DFF DFF
add mapped point u_rf/regs[28][29]/q u_rf/regs_reg[28][29]/Q -type DFF DFF
add mapped point u_rf/regs[28][30]/q u_rf/regs_reg[28][30]/Q -type DFF DFF
add mapped point u_rf/regs[28][31]/q u_rf/regs_reg[28][31]/Q -type DFF DFF
add mapped point u_rf/regs[29][0]/q u_rf/regs_reg[29][0]/Q -type DFF DFF
add mapped point u_rf/regs[29][1]/q u_rf/regs_reg[29][1]/Q -type DFF DFF
add mapped point u_rf/regs[29][2]/q u_rf/regs_reg[29][2]/Q -type DFF DFF
add mapped point u_rf/regs[29][3]/q u_rf/regs_reg[29][3]/Q -type DFF DFF
add mapped point u_rf/regs[29][4]/q u_rf/regs_reg[29][4]/Q -type DFF DFF
add mapped point u_rf/regs[29][5]/q u_rf/regs_reg[29][5]/Q -type DFF DFF
add mapped point u_rf/regs[29][6]/q u_rf/regs_reg[29][6]/Q -type DFF DFF
add mapped point u_rf/regs[29][7]/q u_rf/regs_reg[29][7]/Q -type DFF DFF
add mapped point u_rf/regs[29][8]/q u_rf/regs_reg[29][8]/Q -type DFF DFF
add mapped point u_rf/regs[29][9]/q u_rf/regs_reg[29][9]/Q -type DFF DFF
add mapped point u_rf/regs[29][10]/q u_rf/regs_reg[29][10]/Q -type DFF DFF
add mapped point u_rf/regs[29][11]/q u_rf/regs_reg[29][11]/Q -type DFF DFF
add mapped point u_rf/regs[29][12]/q u_rf/regs_reg[29][12]/Q -type DFF DFF
add mapped point u_rf/regs[29][13]/q u_rf/regs_reg[29][13]/Q -type DFF DFF
add mapped point u_rf/regs[29][14]/q u_rf/regs_reg[29][14]/Q -type DFF DFF
add mapped point u_rf/regs[29][15]/q u_rf/regs_reg[29][15]/Q -type DFF DFF
add mapped point u_rf/regs[29][16]/q u_rf/regs_reg[29][16]/Q -type DFF DFF
add mapped point u_rf/regs[29][17]/q u_rf/regs_reg[29][17]/Q -type DFF DFF
add mapped point u_rf/regs[29][18]/q u_rf/regs_reg[29][18]/Q -type DFF DFF
add mapped point u_rf/regs[29][19]/q u_rf/regs_reg[29][19]/Q -type DFF DFF
add mapped point u_rf/regs[29][20]/q u_rf/regs_reg[29][20]/Q -type DFF DFF
add mapped point u_rf/regs[29][21]/q u_rf/regs_reg[29][21]/Q -type DFF DFF
add mapped point u_rf/regs[29][22]/q u_rf/regs_reg[29][22]/Q -type DFF DFF
add mapped point u_rf/regs[29][23]/q u_rf/regs_reg[29][23]/Q -type DFF DFF
add mapped point u_rf/regs[29][24]/q u_rf/regs_reg[29][24]/Q -type DFF DFF
add mapped point u_rf/regs[29][25]/q u_rf/regs_reg[29][25]/Q -type DFF DFF
add mapped point u_rf/regs[29][26]/q u_rf/regs_reg[29][26]/Q -type DFF DFF
add mapped point u_rf/regs[29][27]/q u_rf/regs_reg[29][27]/Q -type DFF DFF
add mapped point u_rf/regs[29][28]/q u_rf/regs_reg[29][28]/Q -type DFF DFF
add mapped point u_rf/regs[29][29]/q u_rf/regs_reg[29][29]/Q -type DFF DFF
add mapped point u_rf/regs[29][30]/q u_rf/regs_reg[29][30]/Q -type DFF DFF
add mapped point u_rf/regs[29][31]/q u_rf/regs_reg[29][31]/Q -type DFF DFF
add mapped point u_rf/regs[30][0]/q u_rf/regs_reg[30][0]/Q -type DFF DFF
add mapped point u_rf/regs[30][1]/q u_rf/regs_reg[30][1]/Q -type DFF DFF
add mapped point u_rf/regs[30][2]/q u_rf/regs_reg[30][2]/Q -type DFF DFF
add mapped point u_rf/regs[30][3]/q u_rf/regs_reg[30][3]/Q -type DFF DFF
add mapped point u_rf/regs[30][4]/q u_rf/regs_reg[30][4]/Q -type DFF DFF
add mapped point u_rf/regs[30][5]/q u_rf/regs_reg[30][5]/Q -type DFF DFF
add mapped point u_rf/regs[30][6]/q u_rf/regs_reg[30][6]/Q -type DFF DFF
add mapped point u_rf/regs[30][7]/q u_rf/regs_reg[30][7]/Q -type DFF DFF
add mapped point u_rf/regs[30][8]/q u_rf/regs_reg[30][8]/Q -type DFF DFF
add mapped point u_rf/regs[30][9]/q u_rf/regs_reg[30][9]/Q -type DFF DFF
add mapped point u_rf/regs[30][10]/q u_rf/regs_reg[30][10]/Q -type DFF DFF
add mapped point u_rf/regs[30][11]/q u_rf/regs_reg[30][11]/Q -type DFF DFF
add mapped point u_rf/regs[30][12]/q u_rf/regs_reg[30][12]/Q -type DFF DFF
add mapped point u_rf/regs[30][13]/q u_rf/regs_reg[30][13]/Q -type DFF DFF
add mapped point u_rf/regs[30][14]/q u_rf/regs_reg[30][14]/Q -type DFF DFF
add mapped point u_rf/regs[30][15]/q u_rf/regs_reg[30][15]/Q -type DFF DFF
add mapped point u_rf/regs[30][16]/q u_rf/regs_reg[30][16]/Q -type DFF DFF
add mapped point u_rf/regs[30][17]/q u_rf/regs_reg[30][17]/Q -type DFF DFF
add mapped point u_rf/regs[30][18]/q u_rf/regs_reg[30][18]/Q -type DFF DFF
add mapped point u_rf/regs[30][19]/q u_rf/regs_reg[30][19]/Q -type DFF DFF
add mapped point u_rf/regs[30][20]/q u_rf/regs_reg[30][20]/Q -type DFF DFF
add mapped point u_rf/regs[30][21]/q u_rf/regs_reg[30][21]/Q -type DFF DFF
add mapped point u_rf/regs[30][22]/q u_rf/regs_reg[30][22]/Q -type DFF DFF
add mapped point u_rf/regs[30][23]/q u_rf/regs_reg[30][23]/Q -type DFF DFF
add mapped point u_rf/regs[30][24]/q u_rf/regs_reg[30][24]/Q -type DFF DFF
add mapped point u_rf/regs[30][25]/q u_rf/regs_reg[30][25]/Q -type DFF DFF
add mapped point u_rf/regs[30][26]/q u_rf/regs_reg[30][26]/Q -type DFF DFF
add mapped point u_rf/regs[30][27]/q u_rf/regs_reg[30][27]/Q -type DFF DFF
add mapped point u_rf/regs[30][28]/q u_rf/regs_reg[30][28]/Q -type DFF DFF
add mapped point u_rf/regs[30][29]/q u_rf/regs_reg[30][29]/Q -type DFF DFF
add mapped point u_rf/regs[30][30]/q u_rf/regs_reg[30][30]/Q -type DFF DFF
add mapped point u_rf/regs[30][31]/q u_rf/regs_reg[30][31]/Q -type DFF DFF
add mapped point u_rf/regs[31][0]/q u_rf/regs_reg[31][0]/Q -type DFF DFF
add mapped point u_rf/regs[31][1]/q u_rf/regs_reg[31][1]/Q -type DFF DFF
add mapped point u_rf/regs[31][2]/q u_rf/regs_reg[31][2]/Q -type DFF DFF
add mapped point u_rf/regs[31][3]/q u_rf/regs_reg[31][3]/Q -type DFF DFF
add mapped point u_rf/regs[31][4]/q u_rf/regs_reg[31][4]/Q -type DFF DFF
add mapped point u_rf/regs[31][5]/q u_rf/regs_reg[31][5]/Q -type DFF DFF
add mapped point u_rf/regs[31][6]/q u_rf/regs_reg[31][6]/Q -type DFF DFF
add mapped point u_rf/regs[31][7]/q u_rf/regs_reg[31][7]/Q -type DFF DFF
add mapped point u_rf/regs[31][8]/q u_rf/regs_reg[31][8]/Q -type DFF DFF
add mapped point u_rf/regs[31][9]/q u_rf/regs_reg[31][9]/Q -type DFF DFF
add mapped point u_rf/regs[31][10]/q u_rf/regs_reg[31][10]/Q -type DFF DFF
add mapped point u_rf/regs[31][11]/q u_rf/regs_reg[31][11]/Q -type DFF DFF
add mapped point u_rf/regs[31][12]/q u_rf/regs_reg[31][12]/Q -type DFF DFF
add mapped point u_rf/regs[31][13]/q u_rf/regs_reg[31][13]/Q -type DFF DFF
add mapped point u_rf/regs[31][14]/q u_rf/regs_reg[31][14]/Q -type DFF DFF
add mapped point u_rf/regs[31][15]/q u_rf/regs_reg[31][15]/Q -type DFF DFF
add mapped point u_rf/regs[31][16]/q u_rf/regs_reg[31][16]/Q -type DFF DFF
add mapped point u_rf/regs[31][17]/q u_rf/regs_reg[31][17]/Q -type DFF DFF
add mapped point u_rf/regs[31][18]/q u_rf/regs_reg[31][18]/Q -type DFF DFF
add mapped point u_rf/regs[31][19]/q u_rf/regs_reg[31][19]/Q -type DFF DFF
add mapped point u_rf/regs[31][20]/q u_rf/regs_reg[31][20]/Q -type DFF DFF
add mapped point u_rf/regs[31][21]/q u_rf/regs_reg[31][21]/Q -type DFF DFF
add mapped point u_rf/regs[31][22]/q u_rf/regs_reg[31][22]/Q -type DFF DFF
add mapped point u_rf/regs[31][23]/q u_rf/regs_reg[31][23]/Q -type DFF DFF
add mapped point u_rf/regs[31][24]/q u_rf/regs_reg[31][24]/Q -type DFF DFF
add mapped point u_rf/regs[31][25]/q u_rf/regs_reg[31][25]/Q -type DFF DFF
add mapped point u_rf/regs[31][26]/q u_rf/regs_reg[31][26]/Q -type DFF DFF
add mapped point u_rf/regs[31][27]/q u_rf/regs_reg[31][27]/Q -type DFF DFF
add mapped point u_rf/regs[31][28]/q u_rf/regs_reg[31][28]/Q -type DFF DFF
add mapped point u_rf/regs[31][29]/q u_rf/regs_reg[31][29]/Q -type DFF DFF
add mapped point u_rf/regs[31][30]/q u_rf/regs_reg[31][30]/Q -type DFF DFF
add mapped point u_rf/regs[31][31]/q u_rf/regs_reg[31][31]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
